# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\dev\roam\src\configmanager\editorwidgets\uifiles\listwidget_config.ui'
#
# Created: Fri Jan 31 13:42:24 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(439, 382)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stackedWidget = QtGui.QStackedWidget(Form)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.formLayout = QtGui.QFormLayout(self.page)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.page)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.layerCombo = QtGui.QComboBox(self.page)
        self.layerCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.layerCombo.setFrame(True)
        self.layerCombo.setObjectName(_fromUtf8("layerCombo"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.layerCombo)
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.keyCombo = QtGui.QComboBox(self.page)
        self.keyCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.keyCombo.setModelColumn(0)
        self.keyCombo.setObjectName(_fromUtf8("keyCombo"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.keyCombo)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.valueCombo = QtGui.QComboBox(self.page)
        self.valueCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.valueCombo.setModelColumn(0)
        self.valueCombo.setObjectName(_fromUtf8("valueCombo"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.valueCombo)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.filterButton = QtGui.QToolButton(self.page)
        self.filterButton.setObjectName(_fromUtf8("filterButton"))
        self.horizontalLayout_2.addWidget(self.filterButton)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.filterText = QtGui.QPlainTextEdit(self.page)
        self.filterText.setObjectName(_fromUtf8("filterText"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.filterText)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.listText = QtGui.QPlainTextEdit(self.page_3)
        self.listText.setCenterOnScroll(False)
        self.listText.setObjectName(_fromUtf8("listText"))
        self.gridLayout_4.addWidget(self.listText, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.page_3)
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(89, 89, 89);"))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout.addWidget(self.stackedWidget, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.layerRadio = QtGui.QRadioButton(Form)
        self.layerRadio.setChecked(True)
        self.layerRadio.setObjectName(_fromUtf8("layerRadio"))
        self.horizontalLayout.addWidget(self.layerRadio)
        self.listRadio = QtGui.QRadioButton(Form)
        self.listRadio.setObjectName(_fromUtf8("listRadio"))
        self.horizontalLayout.addWidget(self.listRadio)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.allownullCheck = QtGui.QCheckBox(Form)
        self.allownullCheck.setEnabled(True)
        self.allownullCheck.setObjectName(_fromUtf8("allownullCheck"))
        self.gridLayout.addWidget(self.allownullCheck, 1, 0, 1, 1)
        self.orderbyCheck = QtGui.QCheckBox(Form)
        self.orderbyCheck.setEnabled(False)
        self.orderbyCheck.setObjectName(_fromUtf8("orderbyCheck"))
        self.gridLayout.addWidget(self.orderbyCheck, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.allownullCheck, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), Form.widgetchanged)
        QtCore.QObject.connect(self.orderbyCheck, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), Form.widgetchanged)
        QtCore.QObject.connect(self.layerRadio, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), Form.widgetchanged)
        QtCore.QObject.connect(self.listRadio, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), Form.widgetchanged)
        QtCore.QObject.connect(self.layerCombo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Form.widgetchanged)
        QtCore.QObject.connect(self.keyCombo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Form.widgetchanged)
        QtCore.QObject.connect(self.valueCombo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Form.widgetchanged)
        QtCore.QObject.connect(self.filterText, QtCore.SIGNAL(_fromUtf8("textChanged()")), Form.widgetchanged)
        QtCore.QObject.connect(self.listText, QtCore.SIGNAL(_fromUtf8("textChanged()")), Form.widgetchanged)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Data Column ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Description Column", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.filterButton.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Single item per line. Descriptions can be added after the item using a semicolon e.g Test ; My Testing", None, QtGui.QApplication.UnicodeUTF8))
        self.layerRadio.setText(QtGui.QApplication.translate("Form", "From layer", None, QtGui.QApplication.UnicodeUTF8))
        self.listRadio.setText(QtGui.QApplication.translate("Form", "From pre-defined list", None, QtGui.QApplication.UnicodeUTF8))
        self.allownullCheck.setText(QtGui.QApplication.translate("Form", "Allow Null Value", None, QtGui.QApplication.UnicodeUTF8))
        self.orderbyCheck.setText(QtGui.QApplication.translate("Form", "Order By Value", None, QtGui.QApplication.UnicodeUTF8))

