# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_concept.ui'
#
# Created: Thu Apr 19 11:25:05 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WaterForm(object):
    def setupUi(self, WaterForm):
        WaterForm.setObjectName(_fromUtf8("WaterForm"))
        WaterForm.resize(397, 475)
        WaterForm.setStyleSheet(_fromUtf8("font: 75 12pt \"Tahoma\";"))
        self.gridLayout = QtGui.QGridLayout(WaterForm)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.jobNoLabel = QtGui.QLabel(WaterForm)
        self.jobNoLabel.setObjectName(_fromUtf8("jobNoLabel"))
        self.gridLayout.addWidget(self.jobNoLabel, 0, 0, 1, 1)
        self.UniqueID = QtGui.QLineEdit(WaterForm)
        self.UniqueID.setReadOnly(True)
        self.UniqueID.setObjectName(_fromUtf8("UniqueID"))
        self.gridLayout.addWidget(self.UniqueID, 0, 1, 1, 1)
        self.descriptionLabel = QtGui.QLabel(WaterForm)
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.gridLayout.addWidget(self.descriptionLabel, 1, 0, 1, 1)
        self.TextField = QtGui.QLineEdit(WaterForm)
        self.TextField.setObjectName(_fromUtf8("TextField"))
        self.gridLayout.addWidget(self.TextField, 1, 1, 1, 1)
        self.selectAction = QtGui.QToolButton(WaterForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectAction.sizePolicy().hasHeightForWidth())
        self.selectAction.setSizePolicy(sizePolicy)
        self.selectAction.setMaximumSize(QtCore.QSize(50, 50))
        self.selectAction.setObjectName(_fromUtf8("selectAction"))
        self.gridLayout.addWidget(self.selectAction, 1, 2, 1, 1)
        self.label = QtGui.QLabel(WaterForm)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.CheckBoxField = QtGui.QCheckBox(WaterForm)
        self.CheckBoxField.setObjectName(_fromUtf8("CheckBoxField"))
        self.gridLayout.addWidget(self.CheckBoxField, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(WaterForm)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.ComboField = QtGui.QComboBox(WaterForm)
        self.ComboField.setFrame(True)
        self.ComboField.setObjectName(_fromUtf8("ComboField"))
        self.ComboField.addItem(_fromUtf8(""))
        self.ComboField.setItemText(0, _fromUtf8(""))
        self.ComboField.addItem(_fromUtf8(""))
        self.ComboField.addItem(_fromUtf8(""))
        self.ComboField.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ComboField, 3, 1, 1, 1)
        self.numberLabel = QtGui.QLabel(WaterForm)
        self.numberLabel.setObjectName(_fromUtf8("numberLabel"))
        self.gridLayout.addWidget(self.numberLabel, 4, 0, 1, 1)
        self.NumberField = QtGui.QSpinBox(WaterForm)
        self.NumberField.setMaximum(999999999)
        self.NumberField.setObjectName(_fromUtf8("NumberField"))
        self.gridLayout.addWidget(self.NumberField, 4, 1, 1, 1)
        self.selectLotNumber = QtGui.QToolButton(WaterForm)
        self.selectLotNumber.setObjectName(_fromUtf8("selectLotNumber"))
        self.gridLayout.addWidget(self.selectLotNumber, 4, 2, 1, 1)
        self.label_3 = QtGui.QLabel(WaterForm)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.DecimalField = QtGui.QDoubleSpinBox(WaterForm)
        self.DecimalField.setStyleSheet(_fromUtf8(""))
        self.DecimalField.setObjectName(_fromUtf8("DecimalField"))
        self.gridLayout.addWidget(self.DecimalField, 5, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.DateTimeField = QtGui.QDateTimeEdit(WaterForm)
        self.DateTimeField.setObjectName(_fromUtf8("DateTimeField"))
        self.horizontalLayout.addWidget(self.DateTimeField)
        self.pushButton = QtGui.QPushButton(WaterForm)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 1, 1, 2)
        self.label_4 = QtGui.QLabel(WaterForm)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.DateField = QtGui.QCalendarWidget(WaterForm)
        self.DateField.setObjectName(_fromUtf8("DateField"))
        self.gridLayout.addWidget(self.DateField, 7, 1, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(WaterForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 8, 0, 1, 2)

        self.retranslateUi(WaterForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), WaterForm.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), WaterForm.accept)
        QtCore.QMetaObject.connectSlotsByName(WaterForm)

    def retranslateUi(self, WaterForm):
        WaterForm.setWindowTitle(QtGui.QApplication.translate("WaterForm", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.jobNoLabel.setText(QtGui.QApplication.translate("WaterForm", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionLabel.setText(QtGui.QApplication.translate("WaterForm", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAction.setText(QtGui.QApplication.translate("WaterForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("WaterForm", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.CheckBoxField.setText(QtGui.QApplication.translate("WaterForm", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("WaterForm", "ComboBox", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboField.setItemText(1, QtGui.QApplication.translate("WaterForm", "Test 1", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboField.setItemText(2, QtGui.QApplication.translate("WaterForm", "Test 2", None, QtGui.QApplication.UnicodeUTF8))
        self.ComboField.setItemText(3, QtGui.QApplication.translate("WaterForm", "Test 3", None, QtGui.QApplication.UnicodeUTF8))
        self.numberLabel.setText(QtGui.QApplication.translate("WaterForm", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.selectLotNumber.setText(QtGui.QApplication.translate("WaterForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("WaterForm", "Decimal", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("WaterForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("WaterForm", "Date", None, QtGui.QApplication.UnicodeUTF8))

