# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaterJobSheetDraft1.ui'
#
# Created: Wed May 02 10:52:32 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WaterForm(object):
    def setupUi(self, WaterForm):
        WaterForm.setObjectName(_fromUtf8("WaterForm"))
        WaterForm.resize(1023, 768)
        WaterForm.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    font-weight: bold;\n"
"}"))
        self.buttonBox = QtGui.QDialogButtonBox(WaterForm)
        self.buttonBox.setGeometry(QtCore.QRect(500, 730, 511, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label_3 = QtGui.QLabel(WaterForm)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.InstallationsAndMeterReadsGroup = QtGui.QGroupBox(WaterForm)
        self.InstallationsAndMeterReadsGroup.setGeometry(QtCore.QRect(500, 230, 261, 271))
        self.InstallationsAndMeterReadsGroup.setStyleSheet(_fromUtf8(""))
        self.InstallationsAndMeterReadsGroup.setCheckable(True)
        self.InstallationsAndMeterReadsGroup.setChecked(False)
        self.InstallationsAndMeterReadsGroup.setObjectName(_fromUtf8("InstallationsAndMeterReadsGroup"))
        self.gridLayout_5 = QtGui.QGridLayout(self.InstallationsAndMeterReadsGroup)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_9 = QtGui.QLabel(self.InstallationsAndMeterReadsGroup)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 2)
        self.NewService = QtGui.QCheckBox(self.InstallationsAndMeterReadsGroup)
        self.NewService.setObjectName(_fromUtf8("NewService"))
        self.gridLayout_5.addWidget(self.NewService, 1, 0, 1, 2)
        self.MeterReplaced = QtGui.QCheckBox(self.InstallationsAndMeterReadsGroup)
        self.MeterReplaced.setObjectName(_fromUtf8("MeterReplaced"))
        self.gridLayout_5.addWidget(self.MeterReplaced, 4, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.InstallationsAndMeterReadsGroup)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 8, 0, 1, 1)
        self.ExistingMeterNumber = QtGui.QLineEdit(self.InstallationsAndMeterReadsGroup)
        self.ExistingMeterNumber.setObjectName(_fromUtf8("ExistingMeterNumber"))
        self.gridLayout_5.addWidget(self.ExistingMeterNumber, 8, 1, 1, 2)
        self.label_6 = QtGui.QLabel(self.InstallationsAndMeterReadsGroup)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 9, 0, 1, 1)
        self.ExistingMeterReadingKL = QtGui.QLineEdit(self.InstallationsAndMeterReadsGroup)
        self.ExistingMeterReadingKL.setObjectName(_fromUtf8("ExistingMeterReadingKL"))
        self.gridLayout_5.addWidget(self.ExistingMeterReadingKL, 9, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.InstallationsAndMeterReadsGroup)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 10, 0, 1, 1)
        self.NewMeterNumber = QtGui.QLineEdit(self.InstallationsAndMeterReadsGroup)
        self.NewMeterNumber.setObjectName(_fromUtf8("NewMeterNumber"))
        self.gridLayout_5.addWidget(self.NewMeterNumber, 10, 1, 1, 2)
        self.label_8 = QtGui.QLabel(self.InstallationsAndMeterReadsGroup)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 11, 0, 1, 1)
        self.NewMeterReadingKL = QtGui.QLineEdit(self.InstallationsAndMeterReadsGroup)
        self.NewMeterReadingKL.setObjectName(_fromUtf8("NewMeterReadingKL"))
        self.gridLayout_5.addWidget(self.NewMeterReadingKL, 11, 1, 1, 2)
        self.InstallationSheetNumber = QtGui.QLineEdit(self.InstallationsAndMeterReadsGroup)
        self.InstallationSheetNumber.setObjectName(_fromUtf8("InstallationSheetNumber"))
        self.gridLayout_5.addWidget(self.InstallationSheetNumber, 0, 2, 1, 1)
        self.FireService = QtGui.QCheckBox(self.InstallationsAndMeterReadsGroup)
        self.FireService.setObjectName(_fromUtf8("FireService"))
        self.gridLayout_5.addWidget(self.FireService, 1, 2, 1, 1)
        self.RelayedService = QtGui.QCheckBox(self.InstallationsAndMeterReadsGroup)
        self.RelayedService.setObjectName(_fromUtf8("RelayedService"))
        self.gridLayout_5.addWidget(self.RelayedService, 4, 2, 1, 1)
        self.MeterRemoved = QtGui.QCheckBox(self.InstallationsAndMeterReadsGroup)
        self.MeterRemoved.setObjectName(_fromUtf8("MeterRemoved"))
        self.gridLayout_5.addWidget(self.MeterRemoved, 5, 2, 1, 1)
        self.DisconnectService = QtGui.QCheckBox(self.InstallationsAndMeterReadsGroup)
        self.DisconnectService.setObjectName(_fromUtf8("DisconnectService"))
        self.gridLayout_5.addWidget(self.DisconnectService, 5, 0, 1, 1)
        self.MeterRead = QtGui.QCheckBox(self.InstallationsAndMeterReadsGroup)
        self.MeterRead.setObjectName(_fromUtf8("MeterRead"))
        self.gridLayout_5.addWidget(self.MeterRead, 6, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(WaterForm)
        self.groupBox_7.setGeometry(QtCore.QRect(501, 519, 261, 105))
        self.groupBox_7.setCheckable(True)
        self.groupBox_7.setChecked(False)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_20 = QtGui.QLabel(self.groupBox_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 0, 0, 1, 1)
        self.TrafficControlPlanUsed = QtGui.QComboBox(self.groupBox_7)
        self.TrafficControlPlanUsed.setObjectName(_fromUtf8("TrafficControlPlanUsed"))
        self.TrafficControlPlanUsed.addItem(_fromUtf8(""))
        self.TrafficControlPlanUsed.setItemText(0, _fromUtf8(""))
        self.TrafficControlPlanUsed.addItem(_fromUtf8(""))
        self.TrafficControlPlanUsed.addItem(_fromUtf8(""))
        self.TrafficControlPlanUsed.addItem(_fromUtf8(""))
        self.TrafficControlPlanUsed.addItem(_fromUtf8(""))
        self.TrafficControlPlanUsed.addItem(_fromUtf8(""))
        self.TrafficControlPlanUsed.addItem(_fromUtf8(""))
        self.TrafficControlPlanUsed.addItem(_fromUtf8(""))
        self.TrafficControlPlanUsed.addItem(_fromUtf8(""))
        self.TrafficControlPlanUsed.addItem(_fromUtf8(""))
        self.TrafficControlPlanUsed.addItem(_fromUtf8(""))
        self.TrafficControlPlanUsed.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.TrafficControlPlanUsed, 0, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox_7)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_3.addWidget(self.label_37, 1, 0, 1, 1)
        self.WorkDurationHours = QtGui.QLineEdit(self.groupBox_7)
        self.WorkDurationHours.setText(_fromUtf8(""))
        self.WorkDurationHours.setObjectName(_fromUtf8("WorkDurationHours"))
        self.gridLayout_3.addWidget(self.WorkDurationHours, 1, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_7)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_3.addWidget(self.label_41, 2, 0, 1, 1)
        self.SignageAlterations = QtGui.QLineEdit(self.groupBox_7)
        self.SignageAlterations.setText(_fromUtf8(""))
        self.SignageAlterations.setObjectName(_fromUtf8("SignageAlterations"))
        self.gridLayout_3.addWidget(self.SignageAlterations, 2, 1, 1, 1)
        self.AssetinformationGroup = QtGui.QGroupBox(WaterForm)
        self.AssetinformationGroup.setGeometry(QtCore.QRect(779, 230, 231, 391))
        self.AssetinformationGroup.setCheckable(True)
        self.AssetinformationGroup.setChecked(False)
        self.AssetinformationGroup.setObjectName(_fromUtf8("AssetinformationGroup"))
        self.formLayout = QtGui.QFormLayout(self.AssetinformationGroup)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.PipeMaterial = QtGui.QComboBox(self.AssetinformationGroup)
        self.PipeMaterial.setObjectName(_fromUtf8("PipeMaterial"))
        self.PipeMaterial.addItem(_fromUtf8(""))
        self.PipeMaterial.setItemText(0, _fromUtf8(""))
        self.PipeMaterial.addItem(_fromUtf8(""))
        self.PipeMaterial.addItem(_fromUtf8(""))
        self.PipeMaterial.addItem(_fromUtf8(""))
        self.PipeMaterial.addItem(_fromUtf8(""))
        self.PipeMaterial.addItem(_fromUtf8(""))
        self.PipeMaterial.addItem(_fromUtf8(""))
        self.PipeMaterial.addItem(_fromUtf8(""))
        self.PipeMaterial.addItem(_fromUtf8(""))
        self.PipeMaterial.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.PipeMaterial)
        self.PipeDiameter = QtGui.QComboBox(self.AssetinformationGroup)
        self.PipeDiameter.setObjectName(_fromUtf8("PipeDiameter"))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.setItemText(0, _fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.PipeDiameter.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.PipeDiameter)
        self.PipeDepth = QtGui.QLineEdit(self.AssetinformationGroup)
        self.PipeDepth.setObjectName(_fromUtf8("PipeDepth"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.PipeDepth)
        self.JointType = QtGui.QComboBox(self.AssetinformationGroup)
        self.JointType.setObjectName(_fromUtf8("JointType"))
        self.JointType.addItem(_fromUtf8(""))
        self.JointType.setItemText(0, _fromUtf8(""))
        self.JointType.addItem(_fromUtf8(""))
        self.JointType.addItem(_fromUtf8(""))
        self.JointType.addItem(_fromUtf8(""))
        self.JointType.addItem(_fromUtf8(""))
        self.JointType.addItem(_fromUtf8(""))
        self.JointType.addItem(_fromUtf8(""))
        self.JointType.addItem(_fromUtf8(""))
        self.JointType.addItem(_fromUtf8(""))
        self.JointType.addItem(_fromUtf8(""))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.JointType)
        self.GroundConditions = QtGui.QComboBox(self.AssetinformationGroup)
        self.GroundConditions.setObjectName(_fromUtf8("GroundConditions"))
        self.GroundConditions.addItem(_fromUtf8(""))
        self.GroundConditions.setItemText(0, _fromUtf8(""))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.GroundConditions)
        self.ValveType = QtGui.QComboBox(self.AssetinformationGroup)
        self.ValveType.setObjectName(_fromUtf8("ValveType"))
        self.ValveType.addItem(_fromUtf8(""))
        self.ValveType.setItemText(0, _fromUtf8(""))
        self.ValveType.addItem(_fromUtf8(""))
        self.ValveType.addItem(_fromUtf8(""))
        self.ValveType.addItem(_fromUtf8(""))
        self.ValveType.addItem(_fromUtf8(""))
        self.ValveType.addItem(_fromUtf8(""))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.ValveType)
        self.ValveStatus = QtGui.QComboBox(self.AssetinformationGroup)
        self.ValveStatus.setObjectName(_fromUtf8("ValveStatus"))
        self.ValveStatus.addItem(_fromUtf8(""))
        self.ValveStatus.setItemText(0, _fromUtf8(""))
        self.ValveStatus.addItem(_fromUtf8(""))
        self.ValveStatus.addItem(_fromUtf8(""))
        self.ValveStatus.addItem(_fromUtf8(""))
        self.ValveStatus.addItem(_fromUtf8(""))
        self.ValveStatus.addItem(_fromUtf8(""))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.ValveStatus)
        self.ValveClosingDirection = QtGui.QComboBox(self.AssetinformationGroup)
        self.ValveClosingDirection.setObjectName(_fromUtf8("ValveClosingDirection"))
        self.ValveClosingDirection.addItem(_fromUtf8(""))
        self.ValveClosingDirection.setItemText(0, _fromUtf8(""))
        self.ValveClosingDirection.addItem(_fromUtf8(""))
        self.ValveClosingDirection.addItem(_fromUtf8(""))
        self.ValveClosingDirection.addItem(_fromUtf8(""))
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.ValveClosingDirection)
        self.Designation = QtGui.QComboBox(self.AssetinformationGroup)
        self.Designation.setObjectName(_fromUtf8("Designation"))
        self.Designation.addItem(_fromUtf8(""))
        self.Designation.setItemText(0, _fromUtf8(""))
        self.Designation.addItem(_fromUtf8(""))
        self.Designation.addItem(_fromUtf8(""))
        self.Designation.addItem(_fromUtf8(""))
        self.Designation.addItem(_fromUtf8(""))
        self.Designation.addItem(_fromUtf8(""))
        self.formLayout.setWidget(17, QtGui.QFormLayout.FieldRole, self.Designation)
        self.label_28 = QtGui.QLabel(self.AssetinformationGroup)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout.setWidget(18, QtGui.QFormLayout.LabelRole, self.label_28)
        self.Scheme = QtGui.QComboBox(self.AssetinformationGroup)
        self.Scheme.setObjectName(_fromUtf8("Scheme"))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.setItemText(0, _fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.formLayout.setWidget(18, QtGui.QFormLayout.FieldRole, self.Scheme)
        self.label_14 = QtGui.QLabel(self.AssetinformationGroup)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(self.AssetinformationGroup)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_36 = QtGui.QLabel(self.AssetinformationGroup)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_36)
        self.label_34 = QtGui.QLabel(self.AssetinformationGroup)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_34)
        self.label_39 = QtGui.QLabel(self.AssetinformationGroup)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_39)
        self.label_10 = QtGui.QLabel(self.AssetinformationGroup)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.AssetinformationGroup)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.AssetinformationGroup)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_40 = QtGui.QLabel(self.AssetinformationGroup)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.formLayout.setWidget(17, QtGui.QFormLayout.LabelRole, self.label_40)
        self.groupBox_6 = QtGui.QGroupBox(WaterForm)
        self.groupBox_6.setGeometry(QtCore.QRect(440, 30, 571, 171))
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.Operators = QtGui.QComboBox(self.groupBox_6)
        self.Operators.setEditable(True)
        self.Operators.setObjectName(_fromUtf8("Operators"))
        self.Operators.addItem(_fromUtf8(""))
        self.Operators.setItemText(0, _fromUtf8(""))
        self.Operators.addItem(_fromUtf8(""))
        self.Operators.setItemText(1, _fromUtf8(""))
        self.Operators.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.Operators, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.FollowUpWorkRequired = QtGui.QCheckBox(self.groupBox_6)
        self.FollowUpWorkRequired.setObjectName(_fromUtf8("FollowUpWorkRequired"))
        self.verticalLayout.addWidget(self.FollowUpWorkRequired)
        self.ConsumerContacted = QtGui.QCheckBox(self.groupBox_6)
        self.ConsumerContacted.setObjectName(_fromUtf8("ConsumerContacted"))
        self.verticalLayout.addWidget(self.ConsumerContacted)
        self.ShutdownDoorknock = QtGui.QCheckBox(self.groupBox_6)
        self.ShutdownDoorknock.setObjectName(_fromUtf8("ShutdownDoorknock"))
        self.verticalLayout.addWidget(self.ShutdownDoorknock)
        self.ShutdownLetter = QtGui.QCheckBox(self.groupBox_6)
        self.ShutdownLetter.setObjectName(_fromUtf8("ShutdownLetter"))
        self.verticalLayout.addWidget(self.ShutdownLetter)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 2, 5, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_29 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_2.addWidget(self.label_29)
        self.RespondTime = QtGui.QDateTimeEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RespondTime.sizePolicy().hasHeightForWidth())
        self.RespondTime.setSizePolicy(sizePolicy)
        self.RespondTime.setObjectName(_fromUtf8("RespondTime"))
        self.horizontalLayout_2.addWidget(self.RespondTime)
        self.RespondTime_pick = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RespondTime_pick.sizePolicy().hasHeightForWidth())
        self.RespondTime_pick.setSizePolicy(sizePolicy)
        self.RespondTime_pick.setObjectName(_fromUtf8("RespondTime_pick"))
        self.horizontalLayout_2.addWidget(self.RespondTime_pick)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_30 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_3.addWidget(self.label_30)
        self.CompletionTime = QtGui.QDateTimeEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CompletionTime.sizePolicy().hasHeightForWidth())
        self.CompletionTime.setSizePolicy(sizePolicy)
        self.CompletionTime.setObjectName(_fromUtf8("CompletionTime"))
        self.horizontalLayout_3.addWidget(self.CompletionTime)
        self.CompletionTime_pick = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CompletionTime_pick.sizePolicy().hasHeightForWidth())
        self.CompletionTime_pick.setSizePolicy(sizePolicy)
        self.CompletionTime_pick.setObjectName(_fromUtf8("CompletionTime_pick"))
        self.horizontalLayout_3.addWidget(self.CompletionTime_pick)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.label_31 = QtGui.QLabel(self.groupBox_6)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 3, 0, 1, 1)
        self.ConnectionsInterrupted = QtGui.QLineEdit(self.groupBox_6)
        self.ConnectionsInterrupted.setText(_fromUtf8(""))
        self.ConnectionsInterrupted.setObjectName(_fromUtf8("ConnectionsInterrupted"))
        self.gridLayout_2.addWidget(self.ConnectionsInterrupted, 3, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_6)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 4, 0, 1, 1)
        self.InterruptionDurationHours = QtGui.QLineEdit(self.groupBox_6)
        self.InterruptionDurationHours.setText(_fromUtf8(""))
        self.InterruptionDurationHours.setObjectName(_fromUtf8("InterruptionDurationHours"))
        self.gridLayout_2.addWidget(self.InterruptionDurationHours, 4, 1, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(WaterForm)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 30, 421, 171))
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_21 = QtGui.QLabel(self.groupBox_10)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout.addWidget(self.label_21)
        self.DateTimeReceived = QtGui.QDateTimeEdit(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DateTimeReceived.sizePolicy().hasHeightForWidth())
        self.DateTimeReceived.setSizePolicy(sizePolicy)
        self.DateTimeReceived.setObjectName(_fromUtf8("DateTimeReceived"))
        self.horizontalLayout.addWidget(self.DateTimeReceived)
        self.DateTimeReceived_pick = QtGui.QPushButton(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DateTimeReceived_pick.sizePolicy().hasHeightForWidth())
        self.DateTimeReceived_pick.setSizePolicy(sizePolicy)
        self.DateTimeReceived_pick.setIconSize(QtCore.QSize(16, 16))
        self.DateTimeReceived_pick.setFlat(False)
        self.DateTimeReceived_pick.setObjectName(_fromUtf8("DateTimeReceived_pick"))
        self.horizontalLayout.addWidget(self.DateTimeReceived_pick)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        self.label_27 = QtGui.QLabel(self.groupBox_10)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 1, 0, 1, 1)
        self.RequestType = QtGui.QComboBox(self.groupBox_10)
        self.RequestType.setObjectName(_fromUtf8("RequestType"))
        self.RequestType.addItem(_fromUtf8(""))
        self.RequestType.setItemText(0, _fromUtf8(""))
        self.RequestType.addItem(_fromUtf8(""))
        self.RequestType.addItem(_fromUtf8(""))
        self.RequestType.addItem(_fromUtf8(""))
        self.RequestType.addItem(_fromUtf8(""))
        self.RequestType.addItem(_fromUtf8(""))
        self.RequestType.addItem(_fromUtf8(""))
        self.RequestType.addItem(_fromUtf8(""))
        self.RequestType.addItem(_fromUtf8(""))
        self.RequestType.addItem(_fromUtf8(""))
        self.RequestType.addItem(_fromUtf8(""))
        self.RequestType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.RequestType, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_10)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 1, 2, 1, 1)
        self.RequestedBy = QtGui.QComboBox(self.groupBox_10)
        self.RequestedBy.setEditable(True)
        self.RequestedBy.setObjectName(_fromUtf8("RequestedBy"))
        self.RequestedBy.addItem(_fromUtf8(""))
        self.RequestedBy.setItemText(0, _fromUtf8(""))
        self.RequestedBy.addItem(_fromUtf8(""))
        self.RequestedBy.addItem(_fromUtf8(""))
        self.RequestedBy.addItem(_fromUtf8(""))
        self.RequestedBy.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.RequestedBy, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_10)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.CustomerRequestNumber = QtGui.QLineEdit(self.groupBox_10)
        self.CustomerRequestNumber.setObjectName(_fromUtf8("CustomerRequestNumber"))
        self.gridLayout.addWidget(self.CustomerRequestNumber, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_10)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.LotPlan = QtGui.QLineEdit(self.groupBox_10)
        self.LotPlan.setObjectName(_fromUtf8("LotPlan"))
        self.gridLayout.addWidget(self.LotPlan, 3, 1, 1, 2)
        self.label_25 = QtGui.QLabel(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 4, 0, 1, 1)
        self.AdditionalLocationDetails = QtGui.QTextEdit(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AdditionalLocationDetails.sizePolicy().hasHeightForWidth())
        self.AdditionalLocationDetails.setSizePolicy(sizePolicy)
        self.AdditionalLocationDetails.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.AdditionalLocationDetails.setObjectName(_fromUtf8("AdditionalLocationDetails"))
        self.gridLayout.addWidget(self.AdditionalLocationDetails, 4, 1, 1, 3)
        self.selectLotPlan = QtGui.QToolButton(self.groupBox_10)
        self.selectLotPlan.setIconSize(QtCore.QSize(24, 24))
        self.selectLotPlan.setObjectName(_fromUtf8("selectLotPlan"))
        self.gridLayout.addWidget(self.selectLotPlan, 3, 3, 1, 1)
        self.ServiceRepairsGroup = QtGui.QGroupBox(WaterForm)
        self.ServiceRepairsGroup.setGeometry(QtCore.QRect(10, 530, 221, 211))
        self.ServiceRepairsGroup.setCheckable(True)
        self.ServiceRepairsGroup.setChecked(False)
        self.ServiceRepairsGroup.setObjectName(_fromUtf8("ServiceRepairsGroup"))
        self.gridLayout_9 = QtGui.QGridLayout(self.ServiceRepairsGroup)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.RepairedServiceClamp = QtGui.QCheckBox(self.ServiceRepairsGroup)
        self.RepairedServiceClamp.setObjectName(_fromUtf8("RepairedServiceClamp"))
        self.gridLayout_9.addWidget(self.RepairedServiceClamp, 0, 0, 1, 1)
        self.RepairedServiceReplaceSection = QtGui.QCheckBox(self.ServiceRepairsGroup)
        self.RepairedServiceReplaceSection.setObjectName(_fromUtf8("RepairedServiceReplaceSection"))
        self.gridLayout_9.addWidget(self.RepairedServiceReplaceSection, 1, 0, 1, 1)
        self.ReplacedStopCock = QtGui.QCheckBox(self.ServiceRepairsGroup)
        self.ReplacedStopCock.setObjectName(_fromUtf8("ReplacedStopCock"))
        self.gridLayout_9.addWidget(self.ReplacedStopCock, 2, 0, 1, 1)
        self.RepairedStopCock = QtGui.QCheckBox(self.ServiceRepairsGroup)
        self.RepairedStopCock.setObjectName(_fromUtf8("RepairedStopCock"))
        self.gridLayout_9.addWidget(self.RepairedStopCock, 3, 0, 1, 1)
        self.TpfnrRepaired = QtGui.QCheckBox(self.ServiceRepairsGroup)
        self.TpfnrRepaired.setObjectName(_fromUtf8("TpfnrRepaired"))
        self.gridLayout_9.addWidget(self.TpfnrRepaired, 4, 0, 1, 1)
        self.TpfnrReplaced = QtGui.QCheckBox(self.ServiceRepairsGroup)
        self.TpfnrReplaced.setObjectName(_fromUtf8("TpfnrReplaced"))
        self.gridLayout_9.addWidget(self.TpfnrReplaced, 5, 0, 1, 1)
        self.TpfnrCapped = QtGui.QCheckBox(self.ServiceRepairsGroup)
        self.TpfnrCapped.setObjectName(_fromUtf8("TpfnrCapped"))
        self.gridLayout_9.addWidget(self.TpfnrCapped, 6, 0, 1, 1)
        self.MainsAndFittingsGroup = QtGui.QGroupBox(WaterForm)
        self.MainsAndFittingsGroup.setGeometry(QtCore.QRect(10, 230, 221, 281))
        self.MainsAndFittingsGroup.setCheckable(True)
        self.MainsAndFittingsGroup.setChecked(False)
        self.MainsAndFittingsGroup.setObjectName(_fromUtf8("MainsAndFittingsGroup"))
        self.gridLayout_8 = QtGui.QGridLayout(self.MainsAndFittingsGroup)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.MainRepairedClamp = QtGui.QCheckBox(self.MainsAndFittingsGroup)
        self.MainRepairedClamp.setObjectName(_fromUtf8("MainRepairedClamp"))
        self.gridLayout_8.addWidget(self.MainRepairedClamp, 0, 0, 1, 2)
        self.MainRepairedReplacedSection = QtGui.QCheckBox(self.MainsAndFittingsGroup)
        self.MainRepairedReplacedSection.setObjectName(_fromUtf8("MainRepairedReplacedSection"))
        self.gridLayout_8.addWidget(self.MainRepairedReplacedSection, 1, 0, 1, 2)
        self.label_38 = QtGui.QLabel(self.MainsAndFittingsGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_8.addWidget(self.label_38, 2, 0, 1, 1)
        self.FailureType = QtGui.QComboBox(self.MainsAndFittingsGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FailureType.sizePolicy().hasHeightForWidth())
        self.FailureType.setSizePolicy(sizePolicy)
        self.FailureType.setObjectName(_fromUtf8("FailureType"))
        self.FailureType.addItem(_fromUtf8(""))
        self.FailureType.setItemText(0, _fromUtf8(""))
        self.FailureType.addItem(_fromUtf8(""))
        self.FailureType.addItem(_fromUtf8(""))
        self.FailureType.addItem(_fromUtf8(""))
        self.FailureType.addItem(_fromUtf8(""))
        self.FailureType.addItem(_fromUtf8(""))
        self.FailureType.addItem(_fromUtf8(""))
        self.FailureType.addItem(_fromUtf8(""))
        self.FailureType.addItem(_fromUtf8(""))
        self.FailureType.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.FailureType, 2, 1, 1, 1)
        self.HydrantRepair = QtGui.QCheckBox(self.MainsAndFittingsGroup)
        self.HydrantRepair.setObjectName(_fromUtf8("HydrantRepair"))
        self.gridLayout_8.addWidget(self.HydrantRepair, 3, 0, 1, 1)
        self.HydrantReplace = QtGui.QCheckBox(self.MainsAndFittingsGroup)
        self.HydrantReplace.setObjectName(_fromUtf8("HydrantReplace"))
        self.gridLayout_8.addWidget(self.HydrantReplace, 4, 0, 1, 2)
        self.HydrantCleanAndMark = QtGui.QCheckBox(self.MainsAndFittingsGroup)
        self.HydrantCleanAndMark.setObjectName(_fromUtf8("HydrantCleanAndMark"))
        self.gridLayout_8.addWidget(self.HydrantCleanAndMark, 5, 0, 1, 2)
        self.HydrantReplaceLid = QtGui.QCheckBox(self.MainsAndFittingsGroup)
        self.HydrantReplaceLid.setObjectName(_fromUtf8("HydrantReplaceLid"))
        self.gridLayout_8.addWidget(self.HydrantReplaceLid, 6, 0, 1, 2)
        self.MainsValveRepair = QtGui.QCheckBox(self.MainsAndFittingsGroup)
        self.MainsValveRepair.setObjectName(_fromUtf8("MainsValveRepair"))
        self.gridLayout_8.addWidget(self.MainsValveRepair, 7, 0, 1, 1)
        self.MainsValveReplace = QtGui.QCheckBox(self.MainsAndFittingsGroup)
        self.MainsValveReplace.setObjectName(_fromUtf8("MainsValveReplace"))
        self.gridLayout_8.addWidget(self.MainsValveReplace, 8, 0, 1, 1)
        self.ReplaceLidValve = QtGui.QCheckBox(self.MainsAndFittingsGroup)
        self.ReplaceLidValve.setObjectName(_fromUtf8("ReplaceLidValve"))
        self.gridLayout_8.addWidget(self.ReplaceLidValve, 9, 0, 1, 2)
        self.ReplaceMarkers = QtGui.QCheckBox(self.MainsAndFittingsGroup)
        self.ReplaceMarkers.setObjectName(_fromUtf8("ReplaceMarkers"))
        self.gridLayout_8.addWidget(self.ReplaceMarkers, 10, 0, 1, 2)
        self.OtherGroup = QtGui.QGroupBox(WaterForm)
        self.OtherGroup.setGeometry(QtCore.QRect(248, 440, 231, 301))
        self.OtherGroup.setCheckable(True)
        self.OtherGroup.setChecked(False)
        self.OtherGroup.setObjectName(_fromUtf8("OtherGroup"))
        self.gridLayout_6 = QtGui.QGridLayout(self.OtherGroup)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.Investigate = QtGui.QCheckBox(self.OtherGroup)
        self.Investigate.setObjectName(_fromUtf8("Investigate"))
        self.gridLayout_6.addWidget(self.Investigate, 0, 0, 1, 1)
        self.ConsumerProblem = QtGui.QCheckBox(self.OtherGroup)
        self.ConsumerProblem.setObjectName(_fromUtf8("ConsumerProblem"))
        self.gridLayout_6.addWidget(self.ConsumerProblem, 1, 0, 1, 2)
        self.CouncilFacility = QtGui.QCheckBox(self.OtherGroup)
        self.CouncilFacility.setObjectName(_fromUtf8("CouncilFacility"))
        self.gridLayout_6.addWidget(self.CouncilFacility, 2, 0, 1, 2)
        self.lab = QtGui.QLabel(self.OtherGroup)
        self.lab.setObjectName(_fromUtf8("lab"))
        self.gridLayout_6.addWidget(self.lab, 3, 0, 1, 1)
        self.ProvideLocation = QtGui.QComboBox(self.OtherGroup)
        self.ProvideLocation.setObjectName(_fromUtf8("ProvideLocation"))
        self.ProvideLocation.addItem(_fromUtf8(""))
        self.ProvideLocation.setItemText(0, _fromUtf8(""))
        self.ProvideLocation.addItem(_fromUtf8(""))
        self.ProvideLocation.addItem(_fromUtf8(""))
        self.ProvideLocation.addItem(_fromUtf8(""))
        self.ProvideLocation.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.ProvideLocation, 3, 1, 1, 1)
        self.BackfillsCleanups = QtGui.QCheckBox(self.OtherGroup)
        self.BackfillsCleanups.setObjectName(_fromUtf8("BackfillsCleanups"))
        self.gridLayout_6.addWidget(self.BackfillsCleanups, 4, 0, 1, 2)
        self.WaterSample = QtGui.QCheckBox(self.OtherGroup)
        self.WaterSample.setObjectName(_fromUtf8("WaterSample"))
        self.gridLayout_6.addWidget(self.WaterSample, 5, 0, 1, 1)
        self.MainsFlushed = QtGui.QCheckBox(self.OtherGroup)
        self.MainsFlushed.setObjectName(_fromUtf8("MainsFlushed"))
        self.gridLayout_6.addWidget(self.MainsFlushed, 6, 0, 1, 1)
        self.MeterCover = QtGui.QCheckBox(self.OtherGroup)
        self.MeterCover.setObjectName(_fromUtf8("MeterCover"))
        self.gridLayout_6.addWidget(self.MeterCover, 7, 0, 1, 2)
        self.label_18 = QtGui.QLabel(self.OtherGroup)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_6.addWidget(self.label_18, 8, 0, 1, 1)
        self.Other = QtGui.QLineEdit(self.OtherGroup)
        self.Other.setObjectName(_fromUtf8("Other"))
        self.gridLayout_6.addWidget(self.Other, 9, 0, 1, 2)
        self.PressureAndFlowGroup = QtGui.QGroupBox(WaterForm)
        self.PressureAndFlowGroup.setGeometry(QtCore.QRect(248, 230, 231, 203))
        self.PressureAndFlowGroup.setCheckable(True)
        self.PressureAndFlowGroup.setChecked(False)
        self.PressureAndFlowGroup.setObjectName(_fromUtf8("PressureAndFlowGroup"))
        self.gridLayout_4 = QtGui.QGridLayout(self.PressureAndFlowGroup)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.PressureTestService = QtGui.QCheckBox(self.PressureAndFlowGroup)
        self.PressureTestService.setObjectName(_fromUtf8("PressureTestService"))
        self.gridLayout_4.addWidget(self.PressureTestService, 0, 0, 1, 3)
        self.HydrantFlowTest = QtGui.QCheckBox(self.PressureAndFlowGroup)
        self.HydrantFlowTest.setObjectName(_fromUtf8("HydrantFlowTest"))
        self.gridLayout_4.addWidget(self.HydrantFlowTest, 4, 0, 1, 3)
        self.PressureTestHydrant = QtGui.QCheckBox(self.PressureAndFlowGroup)
        self.PressureTestHydrant.setObjectName(_fromUtf8("PressureTestHydrant"))
        self.gridLayout_4.addWidget(self.PressureTestHydrant, 1, 0, 1, 3)
        self.ServiceFlowTest = QtGui.QCheckBox(self.PressureAndFlowGroup)
        self.ServiceFlowTest.setObjectName(_fromUtf8("ServiceFlowTest"))
        self.gridLayout_4.addWidget(self.ServiceFlowTest, 5, 0, 1, 3)
        self.label_16 = QtGui.QLabel(self.PressureAndFlowGroup)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 2)
        self.LockupKpa = QtGui.QLineEdit(self.PressureAndFlowGroup)
        self.LockupKpa.setObjectName(_fromUtf8("LockupKpa"))
        self.gridLayout_4.addWidget(self.LockupKpa, 2, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.PressureAndFlowGroup)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 6, 0, 1, 1)
        self.LitresPerMinute = QtGui.QLineEdit(self.PressureAndFlowGroup)
        self.LitresPerMinute.setPlaceholderText(_fromUtf8(""))
        self.LitresPerMinute.setObjectName(_fromUtf8("LitresPerMinute"))
        self.gridLayout_4.addWidget(self.LitresPerMinute, 6, 1, 1, 2)
        self.TestSheetCompleted = QtGui.QCheckBox(self.PressureAndFlowGroup)
        self.TestSheetCompleted.setObjectName(_fromUtf8("TestSheetCompleted"))
        self.gridLayout_4.addWidget(self.TestSheetCompleted, 3, 0, 1, 1)
        self.widget = QtGui.QWidget(WaterForm)
        self.widget.setGeometry(QtCore.QRect(500, 640, 511, 87))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.widget)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_33 = QtGui.QLabel(self.widget)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_7.addWidget(self.label_33, 0, 0, 1, 1)
        self.Drawing = QtGui.QCheckBox(self.widget)
        self.Drawing.setObjectName(_fromUtf8("Drawing"))
        self.gridLayout_7.addWidget(self.Drawing, 0, 1, 1, 1)
        self.WorkMethodStatement = QtGui.QCheckBox(self.widget)
        self.WorkMethodStatement.setObjectName(_fromUtf8("WorkMethodStatement"))
        self.gridLayout_7.addWidget(self.WorkMethodStatement, 0, 2, 1, 1)
        self.Notes = QtGui.QTextEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Notes.sizePolicy().hasHeightForWidth())
        self.Notes.setSizePolicy(sizePolicy)
        self.Notes.setObjectName(_fromUtf8("Notes"))
        self.gridLayout_7.addWidget(self.Notes, 1, 0, 1, 3)

        self.retranslateUi(WaterForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), WaterForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), WaterForm.reject)
        QtCore.QMetaObject.connectSlotsByName(WaterForm)

    def retranslateUi(self, WaterForm):
        WaterForm.setWindowTitle(QtGui.QApplication.translate("WaterForm", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("WaterForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">WATER DAILY JOB SHEET</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.InstallationsAndMeterReadsGroup.setTitle(QtGui.QApplication.translate("WaterForm", "Service Installations and Meter Reads", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("WaterForm", "Installation Sheet No:", None, QtGui.QApplication.UnicodeUTF8))
        self.NewService.setText(QtGui.QApplication.translate("WaterForm", "New Service", None, QtGui.QApplication.UnicodeUTF8))
        self.MeterReplaced.setText(QtGui.QApplication.translate("WaterForm", "Meter Replaced", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("WaterForm", "Existing Meter No:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("WaterForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Existing Meter</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Reading (KL):</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("WaterForm", "New Meter No:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("WaterForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">New Meter</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Reading (KL):</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.FireService.setText(QtGui.QApplication.translate("WaterForm", "New Fire Service", None, QtGui.QApplication.UnicodeUTF8))
        self.RelayedService.setText(QtGui.QApplication.translate("WaterForm", "Relayed Service", None, QtGui.QApplication.UnicodeUTF8))
        self.MeterRemoved.setText(QtGui.QApplication.translate("WaterForm", "Meter Removed", None, QtGui.QApplication.UnicodeUTF8))
        self.DisconnectService.setText(QtGui.QApplication.translate("WaterForm", "Disconnect Service", None, QtGui.QApplication.UnicodeUTF8))
        self.MeterRead.setText(QtGui.QApplication.translate("WaterForm", "Meter Read", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("WaterForm", "Traffic Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("WaterForm", "Traffic Control Plan:", None, QtGui.QApplication.UnicodeUTF8))
        self.TrafficControlPlanUsed.setItemText(1, QtGui.QApplication.translate("WaterForm", "Diagram 1", None, QtGui.QApplication.UnicodeUTF8))
        self.TrafficControlPlanUsed.setItemText(2, QtGui.QApplication.translate("WaterForm", "Diagram 2", None, QtGui.QApplication.UnicodeUTF8))
        self.TrafficControlPlanUsed.setItemText(3, QtGui.QApplication.translate("WaterForm", "Diagram 3", None, QtGui.QApplication.UnicodeUTF8))
        self.TrafficControlPlanUsed.setItemText(4, QtGui.QApplication.translate("WaterForm", "Diagram 4", None, QtGui.QApplication.UnicodeUTF8))
        self.TrafficControlPlanUsed.setItemText(5, QtGui.QApplication.translate("WaterForm", "Diagram 5", None, QtGui.QApplication.UnicodeUTF8))
        self.TrafficControlPlanUsed.setItemText(6, QtGui.QApplication.translate("WaterForm", "Diagram 5a", None, QtGui.QApplication.UnicodeUTF8))
        self.TrafficControlPlanUsed.setItemText(7, QtGui.QApplication.translate("WaterForm", "Diagram 6", None, QtGui.QApplication.UnicodeUTF8))
        self.TrafficControlPlanUsed.setItemText(8, QtGui.QApplication.translate("WaterForm", "Diagram 7", None, QtGui.QApplication.UnicodeUTF8))
        self.TrafficControlPlanUsed.setItemText(9, QtGui.QApplication.translate("WaterForm", "Diagram 39", None, QtGui.QApplication.UnicodeUTF8))
        self.TrafficControlPlanUsed.setItemText(10, QtGui.QApplication.translate("WaterForm", "Diagram 43", None, QtGui.QApplication.UnicodeUTF8))
        self.TrafficControlPlanUsed.setItemText(11, QtGui.QApplication.translate("WaterForm", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("WaterForm", "Work  Duration (hrs)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("WaterForm", "Signage Alterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.AssetinformationGroup.setTitle(QtGui.QApplication.translate("WaterForm", "Asset Information", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeMaterial.setItemText(1, QtGui.QApplication.translate("WaterForm", "PVC", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeMaterial.setItemText(2, QtGui.QApplication.translate("WaterForm", "AC", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeMaterial.setItemText(3, QtGui.QApplication.translate("WaterForm", "CI", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeMaterial.setItemText(4, QtGui.QApplication.translate("WaterForm", "CICL", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeMaterial.setItemText(5, QtGui.QApplication.translate("WaterForm", "DICL", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeMaterial.setItemText(6, QtGui.QApplication.translate("WaterForm", "Steel", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeMaterial.setItemText(7, QtGui.QApplication.translate("WaterForm", "GI", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeMaterial.setItemText(8, QtGui.QApplication.translate("WaterForm", "PE", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeMaterial.setItemText(9, QtGui.QApplication.translate("WaterForm", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(1, QtGui.QApplication.translate("WaterForm", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(2, QtGui.QApplication.translate("WaterForm", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(3, QtGui.QApplication.translate("WaterForm", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(4, QtGui.QApplication.translate("WaterForm", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(5, QtGui.QApplication.translate("WaterForm", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(6, QtGui.QApplication.translate("WaterForm", "63", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(7, QtGui.QApplication.translate("WaterForm", "75", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(8, QtGui.QApplication.translate("WaterForm", "80", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(9, QtGui.QApplication.translate("WaterForm", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(10, QtGui.QApplication.translate("WaterForm", "110", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(11, QtGui.QApplication.translate("WaterForm", "150", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(12, QtGui.QApplication.translate("WaterForm", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(13, QtGui.QApplication.translate("WaterForm", "225", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(14, QtGui.QApplication.translate("WaterForm", "250", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(15, QtGui.QApplication.translate("WaterForm", "300", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(16, QtGui.QApplication.translate("WaterForm", "375", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(17, QtGui.QApplication.translate("WaterForm", "450", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(18, QtGui.QApplication.translate("WaterForm", "525", None, QtGui.QApplication.UnicodeUTF8))
        self.PipeDiameter.setItemText(19, QtGui.QApplication.translate("WaterForm", "600", None, QtGui.QApplication.UnicodeUTF8))
        self.JointType.setItemText(1, QtGui.QApplication.translate("WaterForm", "Rubber Ring", None, QtGui.QApplication.UnicodeUTF8))
        self.JointType.setItemText(2, QtGui.QApplication.translate("WaterForm", "Flanged", None, QtGui.QApplication.UnicodeUTF8))
        self.JointType.setItemText(3, QtGui.QApplication.translate("WaterForm", "Gibault", None, QtGui.QApplication.UnicodeUTF8))
        self.JointType.setItemText(4, QtGui.QApplication.translate("WaterForm", "Welded", None, QtGui.QApplication.UnicodeUTF8))
        self.JointType.setItemText(5, QtGui.QApplication.translate("WaterForm", "Solvent Welded", None, QtGui.QApplication.UnicodeUTF8))
        self.JointType.setItemText(6, QtGui.QApplication.translate("WaterForm", "Flanged", None, QtGui.QApplication.UnicodeUTF8))
        self.JointType.setItemText(7, QtGui.QApplication.translate("WaterForm", "Lead", None, QtGui.QApplication.UnicodeUTF8))
        self.JointType.setItemText(8, QtGui.QApplication.translate("WaterForm", "Not Seen", None, QtGui.QApplication.UnicodeUTF8))
        self.JointType.setItemText(9, QtGui.QApplication.translate("WaterForm", "Other ", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveType.setItemText(1, QtGui.QApplication.translate("WaterForm", "Sluice", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveType.setItemText(2, QtGui.QApplication.translate("WaterForm", "Butterfly", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveType.setItemText(3, QtGui.QApplication.translate("WaterForm", "Scour", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveType.setItemText(4, QtGui.QApplication.translate("WaterForm", "PRV", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveType.setItemText(5, QtGui.QApplication.translate("WaterForm", "Reflux", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveStatus.setItemText(1, QtGui.QApplication.translate("WaterForm", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveStatus.setItemText(2, QtGui.QApplication.translate("WaterForm", "Closed", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveStatus.setItemText(3, QtGui.QApplication.translate("WaterForm", "Zone", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveStatus.setItemText(4, QtGui.QApplication.translate("WaterForm", "Failed-Open", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveStatus.setItemText(5, QtGui.QApplication.translate("WaterForm", "Failed_Closed", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveClosingDirection.setItemText(1, QtGui.QApplication.translate("WaterForm", "Clockwise", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveClosingDirection.setItemText(2, QtGui.QApplication.translate("WaterForm", "Anti-clockwise", None, QtGui.QApplication.UnicodeUTF8))
        self.ValveClosingDirection.setItemText(3, QtGui.QApplication.translate("WaterForm", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.Designation.setItemText(1, QtGui.QApplication.translate("WaterForm", "Raw Water", None, QtGui.QApplication.UnicodeUTF8))
        self.Designation.setItemText(2, QtGui.QApplication.translate("WaterForm", "Distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.Designation.setItemText(3, QtGui.QApplication.translate("WaterForm", "Reticulation", None, QtGui.QApplication.UnicodeUTF8))
        self.Designation.setItemText(4, QtGui.QApplication.translate("WaterForm", "Constant Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.Designation.setItemText(5, QtGui.QApplication.translate("WaterForm", "Pressure System", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("WaterForm", "Scheme:", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(1, QtGui.QApplication.translate("WaterForm", "Warwick", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(2, QtGui.QApplication.translate("WaterForm", "Yangan", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(3, QtGui.QApplication.translate("WaterForm", "Stanthorpe", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(4, QtGui.QApplication.translate("WaterForm", "Killarney", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(5, QtGui.QApplication.translate("WaterForm", "Wallangarra", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(6, QtGui.QApplication.translate("WaterForm", "Allora", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(7, QtGui.QApplication.translate("WaterForm", "Dalveen", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(8, QtGui.QApplication.translate("WaterForm", "Pratten", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(9, QtGui.QApplication.translate("WaterForm", "Leyburn", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(10, QtGui.QApplication.translate("WaterForm", "Karara", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("WaterForm", "Pipe Material", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("WaterForm", "Pipe Diameter (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("WaterForm", "Pipe depth (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("WaterForm", "Joint Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("WaterForm", "Ground Conditions:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("WaterForm", "Valve Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("WaterForm", "Valve Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("WaterForm", "Valve closing direction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("WaterForm", "Designation:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("WaterForm", "Response", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("WaterForm", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.Operators.setItemText(2, QtGui.QApplication.translate("WaterForm", "Kim", None, QtGui.QApplication.UnicodeUTF8))
        self.FollowUpWorkRequired.setText(QtGui.QApplication.translate("WaterForm", "Follow up Work Required", None, QtGui.QApplication.UnicodeUTF8))
        self.ConsumerContacted.setText(QtGui.QApplication.translate("WaterForm", "Contacted Consumer", None, QtGui.QApplication.UnicodeUTF8))
        self.ShutdownDoorknock.setText(QtGui.QApplication.translate("WaterForm", "Shutdown Notification - door knock", None, QtGui.QApplication.UnicodeUTF8))
        self.ShutdownLetter.setText(QtGui.QApplication.translate("WaterForm", "Shutdown Notification - letter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("WaterForm", "Respond Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.RespondTime_pick.setText(QtGui.QApplication.translate("WaterForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("WaterForm", "Completion Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.CompletionTime_pick.setText(QtGui.QApplication.translate("WaterForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("WaterForm", "Conections Interupted", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("WaterForm", "Interuption Duration (hrs)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("WaterForm", "Request Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("WaterForm", "Received:", None, QtGui.QApplication.UnicodeUTF8))
        self.DateTimeReceived_pick.setText(QtGui.QApplication.translate("WaterForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("WaterForm", "Request Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestType.setItemText(1, QtGui.QApplication.translate("WaterForm", "Water leak", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestType.setItemText(2, QtGui.QApplication.translate("WaterForm", "Leaking service", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestType.setItemText(3, QtGui.QApplication.translate("WaterForm", "Leaking meter", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestType.setItemText(4, QtGui.QApplication.translate("WaterForm", "Meter Won\'t turn off", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestType.setItemText(5, QtGui.QApplication.translate("WaterForm", "Valve", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestType.setItemText(6, QtGui.QApplication.translate("WaterForm", "Hydrant", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestType.setItemText(7, QtGui.QApplication.translate("WaterForm", "Water Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestType.setItemText(8, QtGui.QApplication.translate("WaterForm", "Low Water Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestType.setItemText(9, QtGui.QApplication.translate("WaterForm", "High Water Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestType.setItemText(10, QtGui.QApplication.translate("WaterForm", "Installation", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestType.setItemText(11, QtGui.QApplication.translate("WaterForm", "Programmed Maintenance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("WaterForm", "Requested By:", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestedBy.setItemText(1, QtGui.QApplication.translate("WaterForm", "Louis Van Slobbe", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestedBy.setItemText(2, QtGui.QApplication.translate("WaterForm", "Les Palmer", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestedBy.setItemText(3, QtGui.QApplication.translate("WaterForm", "Office", None, QtGui.QApplication.UnicodeUTF8))
        self.RequestedBy.setItemText(4, QtGui.QApplication.translate("WaterForm", "Call Centre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("WaterForm", "CR Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("WaterForm", "Lot and Plan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("WaterForm", " Location Details:", None, QtGui.QApplication.UnicodeUTF8))
        self.selectLotPlan.setText(QtGui.QApplication.translate("WaterForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.ServiceRepairsGroup.setTitle(QtGui.QApplication.translate("WaterForm", "Service Repairs", None, QtGui.QApplication.UnicodeUTF8))
        self.RepairedServiceClamp.setText(QtGui.QApplication.translate("WaterForm", "Repaired Service - clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.RepairedServiceReplaceSection.setText(QtGui.QApplication.translate("WaterForm", "Repaired Service - replace section", None, QtGui.QApplication.UnicodeUTF8))
        self.ReplacedStopCock.setText(QtGui.QApplication.translate("WaterForm", "Replaced Stop cock", None, QtGui.QApplication.UnicodeUTF8))
        self.RepairedStopCock.setText(QtGui.QApplication.translate("WaterForm", "Repaired Stop cock", None, QtGui.QApplication.UnicodeUTF8))
        self.TpfnrRepaired.setText(QtGui.QApplication.translate("WaterForm", "TPFNR Repaired", None, QtGui.QApplication.UnicodeUTF8))
        self.TpfnrReplaced.setText(QtGui.QApplication.translate("WaterForm", "TPFNR Replaced", None, QtGui.QApplication.UnicodeUTF8))
        self.TpfnrCapped.setText(QtGui.QApplication.translate("WaterForm", "TPFNR Capped", None, QtGui.QApplication.UnicodeUTF8))
        self.MainsAndFittingsGroup.setTitle(QtGui.QApplication.translate("WaterForm", "Mains and Fittings", None, QtGui.QApplication.UnicodeUTF8))
        self.MainRepairedClamp.setText(QtGui.QApplication.translate("WaterForm", "Main Repaired - clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.MainRepairedReplacedSection.setText(QtGui.QApplication.translate("WaterForm", "Main Repaired - replace section", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("WaterForm", "Failure Type", None, QtGui.QApplication.UnicodeUTF8))
        self.FailureType.setItemText(1, QtGui.QApplication.translate("WaterForm", "Circular Fracture", None, QtGui.QApplication.UnicodeUTF8))
        self.FailureType.setItemText(2, QtGui.QApplication.translate("WaterForm", "Longitudinal fracture", None, QtGui.QApplication.UnicodeUTF8))
        self.FailureType.setItemText(3, QtGui.QApplication.translate("WaterForm", "Pipewall softening", None, QtGui.QApplication.UnicodeUTF8))
        self.FailureType.setItemText(4, QtGui.QApplication.translate("WaterForm", "Pin hole", None, QtGui.QApplication.UnicodeUTF8))
        self.FailureType.setItemText(5, QtGui.QApplication.translate("WaterForm", "Large Hole", None, QtGui.QApplication.UnicodeUTF8))
        self.FailureType.setItemText(6, QtGui.QApplication.translate("WaterForm", "Joint", None, QtGui.QApplication.UnicodeUTF8))
        self.FailureType.setItemText(7, QtGui.QApplication.translate("WaterForm", "Tapping", None, QtGui.QApplication.UnicodeUTF8))
        self.FailureType.setItemText(8, QtGui.QApplication.translate("WaterForm", "Other Party Damage", None, QtGui.QApplication.UnicodeUTF8))
        self.FailureType.setItemText(9, QtGui.QApplication.translate("WaterForm", "other", None, QtGui.QApplication.UnicodeUTF8))
        self.HydrantRepair.setText(QtGui.QApplication.translate("WaterForm", "Hydrant Repair", None, QtGui.QApplication.UnicodeUTF8))
        self.HydrantReplace.setText(QtGui.QApplication.translate("WaterForm", "Hydrant Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.HydrantCleanAndMark.setText(QtGui.QApplication.translate("WaterForm", "Hydrant Clean and Mark", None, QtGui.QApplication.UnicodeUTF8))
        self.HydrantReplaceLid.setText(QtGui.QApplication.translate("WaterForm", "Replace Lid - Hydrant", None, QtGui.QApplication.UnicodeUTF8))
        self.MainsValveRepair.setText(QtGui.QApplication.translate("WaterForm", "Valve Repair", None, QtGui.QApplication.UnicodeUTF8))
        self.MainsValveReplace.setText(QtGui.QApplication.translate("WaterForm", "Valve Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.ReplaceLidValve.setText(QtGui.QApplication.translate("WaterForm", "Replace Lid - Valve", None, QtGui.QApplication.UnicodeUTF8))
        self.ReplaceMarkers.setText(QtGui.QApplication.translate("WaterForm", "Replace Markers", None, QtGui.QApplication.UnicodeUTF8))
        self.OtherGroup.setTitle(QtGui.QApplication.translate("WaterForm", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.Investigate.setText(QtGui.QApplication.translate("WaterForm", "Investigation", None, QtGui.QApplication.UnicodeUTF8))
        self.ConsumerProblem.setText(QtGui.QApplication.translate("WaterForm", "Consumer Problem", None, QtGui.QApplication.UnicodeUTF8))
        self.CouncilFacility.setText(QtGui.QApplication.translate("WaterForm", "Council Facility", None, QtGui.QApplication.UnicodeUTF8))
        self.lab.setText(QtGui.QApplication.translate("WaterForm", "Provide Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.ProvideLocation.setItemText(1, QtGui.QApplication.translate("WaterForm", "External Customer", None, QtGui.QApplication.UnicodeUTF8))
        self.ProvideLocation.setItemText(2, QtGui.QApplication.translate("WaterForm", "Parks", None, QtGui.QApplication.UnicodeUTF8))
        self.ProvideLocation.setItemText(3, QtGui.QApplication.translate("WaterForm", "Buildings", None, QtGui.QApplication.UnicodeUTF8))
        self.ProvideLocation.setItemText(4, QtGui.QApplication.translate("WaterForm", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.BackfillsCleanups.setText(QtGui.QApplication.translate("WaterForm", "Backfill/cleanups", None, QtGui.QApplication.UnicodeUTF8))
        self.WaterSample.setText(QtGui.QApplication.translate("WaterForm", "Water Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.MainsFlushed.setText(QtGui.QApplication.translate("WaterForm", "Mains Flushed", None, QtGui.QApplication.UnicodeUTF8))
        self.MeterCover.setText(QtGui.QApplication.translate("WaterForm", "Meter Cover Provided", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("WaterForm", "Other:", None, QtGui.QApplication.UnicodeUTF8))
        self.PressureAndFlowGroup.setTitle(QtGui.QApplication.translate("WaterForm", "Pressure and Flow", None, QtGui.QApplication.UnicodeUTF8))
        self.PressureTestService.setText(QtGui.QApplication.translate("WaterForm", "Pressure Test Service", None, QtGui.QApplication.UnicodeUTF8))
        self.HydrantFlowTest.setText(QtGui.QApplication.translate("WaterForm", "Hydrant Flow Test", None, QtGui.QApplication.UnicodeUTF8))
        self.PressureTestHydrant.setText(QtGui.QApplication.translate("WaterForm", "Pressure Test Hydrant", None, QtGui.QApplication.UnicodeUTF8))
        self.ServiceFlowTest.setText(QtGui.QApplication.translate("WaterForm", "Service Flow Test", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("WaterForm", "Lockup (KPA):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("WaterForm", "(L/min):", None, QtGui.QApplication.UnicodeUTF8))
        self.TestSheetCompleted.setText(QtGui.QApplication.translate("WaterForm", "Test Sheet completed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("WaterForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Notes:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Drawing.setText(QtGui.QApplication.translate("WaterForm", "Drawing", None, QtGui.QApplication.UnicodeUTF8))
        self.WorkMethodStatement.setText(QtGui.QApplication.translate("WaterForm", "Work Method Statement Completed", None, QtGui.QApplication.UnicodeUTF8))
        self.Notes.setHtml(QtGui.QApplication.translate("WaterForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

