# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaterJobSheetDraft1.ui'
#
# Created: Thu Apr 19 15:52:47 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WaterForm(object):
    def setupUi(self, WaterForm):
        WaterForm.setObjectName(_fromUtf8("WaterForm"))
        WaterForm.resize(925, 863)
        self.buttonBox = QtGui.QDialogButtonBox(WaterForm)
        self.buttonBox.setGeometry(QtCore.QRect(710, 820, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label_3 = QtGui.QLabel(WaterForm)
        self.label_3.setGeometry(QtCore.QRect(310, 0, 251, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_13 = QtGui.QLabel(WaterForm)
        self.label_13.setGeometry(QtCore.QRect(330, 200, 211, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_33 = QtGui.QLabel(WaterForm)
        self.label_33.setGeometry(QtCore.QRect(0, 740, 51, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.Notes = QtGui.QTextEdit(WaterForm)
        self.Notes.setGeometry(QtCore.QRect(0, 760, 881, 61))
        self.Notes.setObjectName(_fromUtf8("Notes"))
        self.groupBox = QtGui.QGroupBox(WaterForm)
        self.groupBox.setGeometry(QtCore.QRect(440, 230, 252, 339))
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 2)
        self.Installation_Sheet_No = QtGui.QLineEdit(self.groupBox)
        self.Installation_Sheet_No.setObjectName(_fromUtf8("Installation_Sheet_No"))
        self.gridLayout_5.addWidget(self.Installation_Sheet_No, 0, 2, 1, 1)
        self.New_Service = QtGui.QCheckBox(self.groupBox)
        self.New_Service.setObjectName(_fromUtf8("New_Service"))
        self.gridLayout_5.addWidget(self.New_Service, 1, 0, 1, 2)
        self.Fire_Service = QtGui.QCheckBox(self.groupBox)
        self.Fire_Service.setObjectName(_fromUtf8("Fire_Service"))
        self.gridLayout_5.addWidget(self.Fire_Service, 2, 0, 1, 2)
        self.Relayed_Service = QtGui.QCheckBox(self.groupBox)
        self.Relayed_Service.setObjectName(_fromUtf8("Relayed_Service"))
        self.gridLayout_5.addWidget(self.Relayed_Service, 3, 0, 1, 2)
        self.Meter_Replaced = QtGui.QCheckBox(self.groupBox)
        self.Meter_Replaced.setObjectName(_fromUtf8("Meter_Replaced"))
        self.gridLayout_5.addWidget(self.Meter_Replaced, 4, 0, 1, 2)
        self.Meter_Removed = QtGui.QCheckBox(self.groupBox)
        self.Meter_Removed.setObjectName(_fromUtf8("Meter_Removed"))
        self.gridLayout_5.addWidget(self.Meter_Removed, 5, 0, 1, 2)
        self.Disconnect_Service = QtGui.QCheckBox(self.groupBox)
        self.Disconnect_Service.setObjectName(_fromUtf8("Disconnect_Service"))
        self.gridLayout_5.addWidget(self.Disconnect_Service, 6, 0, 1, 2)
        self.Meter_Read = QtGui.QCheckBox(self.groupBox)
        self.Meter_Read.setObjectName(_fromUtf8("Meter_Read"))
        self.gridLayout_5.addWidget(self.Meter_Read, 7, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 8, 0, 1, 1)
        self.Existing_Meter_No = QtGui.QLineEdit(self.groupBox)
        self.Existing_Meter_No.setObjectName(_fromUtf8("Existing_Meter_No"))
        self.gridLayout_5.addWidget(self.Existing_Meter_No, 8, 1, 1, 2)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 9, 0, 1, 1)
        self.Existing_Meter_Reading_KL = QtGui.QLineEdit(self.groupBox)
        self.Existing_Meter_Reading_KL.setObjectName(_fromUtf8("Existing_Meter_Reading_KL"))
        self.gridLayout_5.addWidget(self.Existing_Meter_Reading_KL, 9, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 10, 0, 1, 1)
        self.New_Meter_Number = QtGui.QLineEdit(self.groupBox)
        self.New_Meter_Number.setObjectName(_fromUtf8("New_Meter_Number"))
        self.gridLayout_5.addWidget(self.New_Meter_Number, 10, 1, 1, 2)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 11, 0, 1, 1)
        self.New_Meter_Reading_KL = QtGui.QLineEdit(self.groupBox)
        self.New_Meter_Reading_KL.setObjectName(_fromUtf8("New_Meter_Reading_KL"))
        self.gridLayout_5.addWidget(self.New_Meter_Reading_KL, 11, 1, 1, 2)
        self.groupBox_7 = QtGui.QGroupBox(WaterForm)
        self.groupBox_7.setGeometry(QtCore.QRect(440, 590, 451, 111))
        self.groupBox_7.setCheckable(True)
        self.groupBox_7.setChecked(False)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_20 = QtGui.QLabel(self.groupBox_7)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.Traffic_Control_Plan_Used = QtGui.QComboBox(self.groupBox_7)
        self.Traffic_Control_Plan_Used.setGeometry(QtCore.QRect(110, 20, 101, 22))
        self.Traffic_Control_Plan_Used.setObjectName(_fromUtf8("Traffic_Control_Plan_Used"))
        self.Traffic_Control_Plan_Used.addItem(_fromUtf8(""))
        self.Traffic_Control_Plan_Used.setItemText(0, _fromUtf8(""))
        self.Traffic_Control_Plan_Used.addItem(_fromUtf8(""))
        self.Traffic_Control_Plan_Used.addItem(_fromUtf8(""))
        self.Traffic_Control_Plan_Used.addItem(_fromUtf8(""))
        self.Traffic_Control_Plan_Used.addItem(_fromUtf8(""))
        self.Traffic_Control_Plan_Used.addItem(_fromUtf8(""))
        self.Traffic_Control_Plan_Used.addItem(_fromUtf8(""))
        self.Traffic_Control_Plan_Used.addItem(_fromUtf8(""))
        self.Traffic_Control_Plan_Used.addItem(_fromUtf8(""))
        self.Traffic_Control_Plan_Used.addItem(_fromUtf8(""))
        self.Traffic_Control_Plan_Used.addItem(_fromUtf8(""))
        self.Traffic_Control_Plan_Used.addItem(_fromUtf8(""))
        self.label_37 = QtGui.QLabel(self.groupBox_7)
        self.label_37.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.Work_Duration = QtGui.QLineEdit(self.groupBox_7)
        self.Work_Duration.setGeometry(QtCore.QRect(110, 50, 81, 20))
        self.Work_Duration.setText(_fromUtf8(""))
        self.Work_Duration.setObjectName(_fromUtf8("Work_Duration"))
        self.label_35 = QtGui.QLabel(self.groupBox_7)
        self.label_35.setGeometry(QtCore.QRect(240, 30, 171, 41))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_41 = QtGui.QLabel(self.groupBox_7)
        self.label_41.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.Signage_alterations = QtGui.QLineEdit(self.groupBox_7)
        self.Signage_alterations.setGeometry(QtCore.QRect(120, 80, 321, 20))
        self.Signage_alterations.setText(_fromUtf8(""))
        self.Signage_alterations.setObjectName(_fromUtf8("Signage_alterations"))
        self.groupBox_8 = QtGui.QGroupBox(WaterForm)
        self.groupBox_8.setGeometry(QtCore.QRect(700, 230, 221, 289))
        self.groupBox_8.setCheckable(True)
        self.groupBox_8.setChecked(False)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_14 = QtGui.QLabel(self.groupBox_8)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 0, 0, 1, 2)
        self.Pipe_Material = QtGui.QComboBox(self.groupBox_8)
        self.Pipe_Material.setObjectName(_fromUtf8("Pipe_Material"))
        self.Pipe_Material.addItem(_fromUtf8(""))
        self.Pipe_Material.setItemText(0, _fromUtf8(""))
        self.Pipe_Material.addItem(_fromUtf8(""))
        self.Pipe_Material.addItem(_fromUtf8(""))
        self.Pipe_Material.addItem(_fromUtf8(""))
        self.Pipe_Material.addItem(_fromUtf8(""))
        self.Pipe_Material.addItem(_fromUtf8(""))
        self.Pipe_Material.addItem(_fromUtf8(""))
        self.Pipe_Material.addItem(_fromUtf8(""))
        self.Pipe_Material.addItem(_fromUtf8(""))
        self.Pipe_Material.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Pipe_Material, 0, 3, 1, 4)
        self.label_15 = QtGui.QLabel(self.groupBox_8)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_6.addWidget(self.label_15, 1, 0, 1, 5)
        self.Pipe_Diameter = QtGui.QComboBox(self.groupBox_8)
        self.Pipe_Diameter.setObjectName(_fromUtf8("Pipe_Diameter"))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.setItemText(0, _fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.Pipe_Diameter.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Pipe_Diameter, 1, 5, 1, 2)
        self.label_36 = QtGui.QLabel(self.groupBox_8)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_6.addWidget(self.label_36, 2, 0, 1, 3)
        self.Pipe_depth = QtGui.QLineEdit(self.groupBox_8)
        self.Pipe_depth.setObjectName(_fromUtf8("Pipe_depth"))
        self.gridLayout_6.addWidget(self.Pipe_depth, 2, 4, 1, 3)
        self.label_34 = QtGui.QLabel(self.groupBox_8)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_6.addWidget(self.label_34, 3, 0, 1, 1)
        self.Joint_Type = QtGui.QComboBox(self.groupBox_8)
        self.Joint_Type.setObjectName(_fromUtf8("Joint_Type"))
        self.Joint_Type.addItem(_fromUtf8(""))
        self.Joint_Type.setItemText(0, _fromUtf8(""))
        self.Joint_Type.addItem(_fromUtf8(""))
        self.Joint_Type.addItem(_fromUtf8(""))
        self.Joint_Type.addItem(_fromUtf8(""))
        self.Joint_Type.addItem(_fromUtf8(""))
        self.Joint_Type.addItem(_fromUtf8(""))
        self.Joint_Type.addItem(_fromUtf8(""))
        self.Joint_Type.addItem(_fromUtf8(""))
        self.Joint_Type.addItem(_fromUtf8(""))
        self.Joint_Type.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Joint_Type, 3, 2, 1, 5)
        self.label_39 = QtGui.QLabel(self.groupBox_8)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_6.addWidget(self.label_39, 4, 0, 1, 4)
        self.Ground_conditions = QtGui.QComboBox(self.groupBox_8)
        self.Ground_conditions.setObjectName(_fromUtf8("Ground_conditions"))
        self.gridLayout_6.addWidget(self.Ground_conditions, 4, 4, 1, 3)
        self.label_10 = QtGui.QLabel(self.groupBox_8)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 5, 0, 1, 1)
        self.Valve_Type = QtGui.QComboBox(self.groupBox_8)
        self.Valve_Type.setObjectName(_fromUtf8("Valve_Type"))
        self.Valve_Type.addItem(_fromUtf8(""))
        self.Valve_Type.setItemText(0, _fromUtf8(""))
        self.Valve_Type.addItem(_fromUtf8(""))
        self.Valve_Type.addItem(_fromUtf8(""))
        self.Valve_Type.addItem(_fromUtf8(""))
        self.Valve_Type.addItem(_fromUtf8(""))
        self.Valve_Type.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Valve_Type, 5, 2, 1, 5)
        self.label_11 = QtGui.QLabel(self.groupBox_8)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 6, 0, 1, 2)
        self.Valve_Status = QtGui.QComboBox(self.groupBox_8)
        self.Valve_Status.setObjectName(_fromUtf8("Valve_Status"))
        self.Valve_Status.addItem(_fromUtf8(""))
        self.Valve_Status.setItemText(0, _fromUtf8(""))
        self.Valve_Status.addItem(_fromUtf8(""))
        self.Valve_Status.addItem(_fromUtf8(""))
        self.Valve_Status.addItem(_fromUtf8(""))
        self.Valve_Status.addItem(_fromUtf8(""))
        self.Valve_Status.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Valve_Status, 6, 2, 1, 5)
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 7, 0, 1, 6)
        self.Valve_Closing_Direction = QtGui.QComboBox(self.groupBox_8)
        self.Valve_Closing_Direction.setObjectName(_fromUtf8("Valve_Closing_Direction"))
        self.Valve_Closing_Direction.addItem(_fromUtf8(""))
        self.Valve_Closing_Direction.setItemText(0, _fromUtf8(""))
        self.Valve_Closing_Direction.addItem(_fromUtf8(""))
        self.Valve_Closing_Direction.addItem(_fromUtf8(""))
        self.Valve_Closing_Direction.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Valve_Closing_Direction, 7, 6, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_8)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_6.addWidget(self.label_40, 8, 0, 1, 2)
        self.Designation = QtGui.QComboBox(self.groupBox_8)
        self.Designation.setObjectName(_fromUtf8("Designation"))
        self.Designation.addItem(_fromUtf8(""))
        self.Designation.setItemText(0, _fromUtf8(""))
        self.Designation.addItem(_fromUtf8(""))
        self.Designation.addItem(_fromUtf8(""))
        self.Designation.addItem(_fromUtf8(""))
        self.Designation.addItem(_fromUtf8(""))
        self.Designation.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Designation, 8, 2, 1, 5)
        self.label_28 = QtGui.QLabel(self.groupBox_8)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_6.addWidget(self.label_28, 9, 0, 1, 1)
        self.Scheme = QtGui.QComboBox(self.groupBox_8)
        self.Scheme.setObjectName(_fromUtf8("Scheme"))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.setItemText(0, _fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.Scheme.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Scheme, 9, 1, 1, 6)
        self.groupBox_6 = QtGui.QGroupBox(WaterForm)
        self.groupBox_6.setGeometry(QtCore.QRect(440, 20, 608, 187))
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.Operators = QtGui.QComboBox(self.groupBox_6)
        self.Operators.setEditable(True)
        self.Operators.setObjectName(_fromUtf8("Operators"))
        self.Operators.addItem(_fromUtf8(""))
        self.Operators.setItemText(0, _fromUtf8(""))
        self.Operators.addItem(_fromUtf8(""))
        self.Operators.setItemText(1, _fromUtf8(""))
        self.Operators.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.Operators, 0, 1, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_29 = QtGui.QLabel(self.groupBox_6)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_2.addWidget(self.label_29)
        self.Respond_time = QtGui.QDateTimeEdit(self.groupBox_6)
        self.Respond_time.setObjectName(_fromUtf8("Respond_time"))
        self.horizontalLayout_2.addWidget(self.Respond_time)
        self.pushButton = QtGui.QPushButton(self.groupBox_6)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_30 = QtGui.QLabel(self.groupBox_6)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_3.addWidget(self.label_30)
        self.Completion_Time = QtGui.QDateTimeEdit(self.groupBox_6)
        self.Completion_Time.setObjectName(_fromUtf8("Completion_Time"))
        self.horizontalLayout_3.addWidget(self.Completion_Time)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 3)
        self.label_31 = QtGui.QLabel(self.groupBox_6)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 3, 0, 1, 1)
        self.No_Connections_Interupted = QtGui.QLineEdit(self.groupBox_6)
        self.No_Connections_Interupted.setText(_fromUtf8(""))
        self.No_Connections_Interupted.setObjectName(_fromUtf8("No_Connections_Interupted"))
        self.gridLayout.addWidget(self.No_Connections_Interupted, 3, 1, 1, 2)
        self.label_32 = QtGui.QLabel(self.groupBox_6)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.label_32, 3, 3, 1, 1)
        self.Interuption_Duration = QtGui.QLineEdit(self.groupBox_6)
        self.Interuption_Duration.setText(_fromUtf8(""))
        self.Interuption_Duration.setObjectName(_fromUtf8("Interuption_Duration"))
        self.gridLayout.addWidget(self.Interuption_Duration, 3, 4, 1, 1)
        self.Contacted_Consumer = QtGui.QCheckBox(self.groupBox_6)
        self.Contacted_Consumer.setObjectName(_fromUtf8("Contacted_Consumer"))
        self.gridLayout.addWidget(self.Contacted_Consumer, 4, 0, 1, 1)
        self.Follow_up_Work_Required = QtGui.QCheckBox(self.groupBox_6)
        self.Follow_up_Work_Required.setObjectName(_fromUtf8("Follow_up_Work_Required"))
        self.gridLayout.addWidget(self.Follow_up_Work_Required, 4, 2, 1, 1)
        self.Shutdown_Letter = QtGui.QCheckBox(self.groupBox_6)
        self.Shutdown_Letter.setObjectName(_fromUtf8("Shutdown_Letter"))
        self.gridLayout.addWidget(self.Shutdown_Letter, 5, 0, 1, 2)
        self.Shutdown_doorknock = QtGui.QCheckBox(self.groupBox_6)
        self.Shutdown_doorknock.setObjectName(_fromUtf8("Shutdown_doorknock"))
        self.gridLayout.addWidget(self.Shutdown_doorknock, 5, 2, 1, 2)
        self.groupBox_10 = QtGui.QGroupBox(WaterForm)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 20, 401, 171))
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.Request_Type = QtGui.QComboBox(self.groupBox_10)
        self.Request_Type.setGeometry(QtCore.QRect(80, 100, 101, 22))
        self.Request_Type.setObjectName(_fromUtf8("Request_Type"))
        self.Request_Type.addItem(_fromUtf8(""))
        self.Request_Type.setItemText(0, _fromUtf8(""))
        self.Request_Type.addItem(_fromUtf8(""))
        self.Request_Type.addItem(_fromUtf8(""))
        self.Request_Type.addItem(_fromUtf8(""))
        self.Request_Type.addItem(_fromUtf8(""))
        self.Request_Type.addItem(_fromUtf8(""))
        self.Request_Type.addItem(_fromUtf8(""))
        self.Request_Type.addItem(_fromUtf8(""))
        self.Request_Type.addItem(_fromUtf8(""))
        self.Request_Type.addItem(_fromUtf8(""))
        self.Request_Type.addItem(_fromUtf8(""))
        self.Request_Type.addItem(_fromUtf8(""))
        self.label_27 = QtGui.QLabel(self.groupBox_10)
        self.label_27.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_2 = QtGui.QLabel(self.groupBox_10)
        self.label_2.setGeometry(QtCore.QRect(210, 110, 61, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Customer_Request_Number = QtGui.QLineEdit(self.groupBox_10)
        self.Customer_Request_Number.setGeometry(QtCore.QRect(270, 110, 71, 20))
        self.Customer_Request_Number.setObjectName(_fromUtf8("Customer_Request_Number"))
        self.label_22 = QtGui.QLabel(self.groupBox_10)
        self.label_22.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.Requested_by = QtGui.QComboBox(self.groupBox_10)
        self.Requested_by.setGeometry(QtCore.QRect(80, 70, 131, 22))
        self.Requested_by.setEditable(True)
        self.Requested_by.setObjectName(_fromUtf8("Requested_by"))
        self.Requested_by.addItem(_fromUtf8(""))
        self.Requested_by.setItemText(0, _fromUtf8(""))
        self.Requested_by.addItem(_fromUtf8(""))
        self.Requested_by.addItem(_fromUtf8(""))
        self.Requested_by.addItem(_fromUtf8(""))
        self.Requested_by.addItem(_fromUtf8(""))
        self.Additional_Location_Details = QtGui.QTextEdit(self.groupBox_10)
        self.Additional_Location_Details.setGeometry(QtCore.QRect(110, 130, 200, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Additional_Location_Details.sizePolicy().hasHeightForWidth())
        self.Additional_Location_Details.setSizePolicy(sizePolicy)
        self.Additional_Location_Details.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Additional_Location_Details.setObjectName(_fromUtf8("Additional_Location_Details"))
        self.label_25 = QtGui.QLabel(self.groupBox_10)
        self.label_25.setGeometry(QtCore.QRect(10, 140, 91, 20))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.widget = QtGui.QWidget(self.groupBox_10)
        self.widget.setGeometry(QtCore.QRect(10, 20, 285, 25))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_21 = QtGui.QLabel(self.widget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout.addWidget(self.label_21)
        self.Date_Time_Received = QtGui.QDateTimeEdit(self.widget)
        self.Date_Time_Received.setObjectName(_fromUtf8("Date_Time_Received"))
        self.horizontalLayout.addWidget(self.Date_Time_Received)
        self.pushButton_2 = QtGui.QPushButton(self.widget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.Drawing = QtGui.QCheckBox(WaterForm)
        self.Drawing.setGeometry(QtCore.QRect(480, 730, 140, 18))
        self.Drawing.setObjectName(_fromUtf8("Drawing"))
        self.Work_method_statement = QtGui.QCheckBox(WaterForm)
        self.Work_method_statement.setGeometry(QtCore.QRect(610, 730, 201, 18))
        self.Work_method_statement.setObjectName(_fromUtf8("Work_method_statement"))
        self.groupBox_2 = QtGui.QGroupBox(WaterForm)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 520, 215, 211))
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.Repaired_Service_clamp = QtGui.QCheckBox(self.groupBox_2)
        self.Repaired_Service_clamp.setGeometry(QtCore.QRect(10, 30, 151, 18))
        self.Repaired_Service_clamp.setObjectName(_fromUtf8("Repaired_Service_clamp"))
        self.Repaired_Stop_Cock = QtGui.QCheckBox(self.groupBox_2)
        self.Repaired_Stop_Cock.setGeometry(QtCore.QRect(10, 98, 116, 18))
        self.Repaired_Stop_Cock.setObjectName(_fromUtf8("Repaired_Stop_Cock"))
        self.TPFNR_Repaired = QtGui.QCheckBox(self.groupBox_2)
        self.TPFNR_Repaired.setGeometry(QtCore.QRect(10, 122, 102, 18))
        self.TPFNR_Repaired.setObjectName(_fromUtf8("TPFNR_Repaired"))
        self.TPFNR_Replaced = QtGui.QCheckBox(self.groupBox_2)
        self.TPFNR_Replaced.setGeometry(QtCore.QRect(10, 146, 103, 18))
        self.TPFNR_Replaced.setObjectName(_fromUtf8("TPFNR_Replaced"))
        self.TPFNR_Capped = QtGui.QCheckBox(self.groupBox_2)
        self.TPFNR_Capped.setGeometry(QtCore.QRect(10, 170, 96, 18))
        self.TPFNR_Capped.setObjectName(_fromUtf8("TPFNR_Capped"))
        self.Replaced_Stop_Cock = QtGui.QCheckBox(self.groupBox_2)
        self.Replaced_Stop_Cock.setGeometry(QtCore.QRect(10, 74, 117, 18))
        self.Replaced_Stop_Cock.setObjectName(_fromUtf8("Replaced_Stop_Cock"))
        self.Repaired_Service_replace_section = QtGui.QCheckBox(self.groupBox_2)
        self.Repaired_Service_replace_section.setGeometry(QtCore.QRect(10, 50, 191, 18))
        self.Repaired_Service_replace_section.setObjectName(_fromUtf8("Repaired_Service_replace_section"))
        self.groupBox_3 = QtGui.QGroupBox(WaterForm)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 220, 215, 291))
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.Main_repaired_clamp = QtGui.QCheckBox(self.groupBox_3)
        self.Main_repaired_clamp.setGeometry(QtCore.QRect(11, 24, 131, 18))
        self.Main_repaired_clamp.setObjectName(_fromUtf8("Main_repaired_clamp"))
        self.label_38 = QtGui.QLabel(self.groupBox_3)
        self.label_38.setGeometry(QtCore.QRect(14, 80, 57, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.Failure_type = QtGui.QComboBox(self.groupBox_3)
        self.Failure_type.setGeometry(QtCore.QRect(110, 80, 97, 20))
        self.Failure_type.setObjectName(_fromUtf8("Failure_type"))
        self.Failure_type.addItem(_fromUtf8(""))
        self.Failure_type.setItemText(0, _fromUtf8(""))
        self.Failure_type.addItem(_fromUtf8(""))
        self.Failure_type.addItem(_fromUtf8(""))
        self.Failure_type.addItem(_fromUtf8(""))
        self.Failure_type.addItem(_fromUtf8(""))
        self.Failure_type.addItem(_fromUtf8(""))
        self.Failure_type.addItem(_fromUtf8(""))
        self.Failure_type.addItem(_fromUtf8(""))
        self.Failure_type.addItem(_fromUtf8(""))
        self.Failure_type.addItem(_fromUtf8(""))
        self.Hydrant_Repair = QtGui.QCheckBox(self.groupBox_3)
        self.Hydrant_Repair.setGeometry(QtCore.QRect(10, 110, 97, 18))
        self.Hydrant_Repair.setObjectName(_fromUtf8("Hydrant_Repair"))
        self.Hydrant_Replace = QtGui.QCheckBox(self.groupBox_3)
        self.Hydrant_Replace.setGeometry(QtCore.QRect(10, 134, 104, 18))
        self.Hydrant_Replace.setObjectName(_fromUtf8("Hydrant_Replace"))
        self.Hydrant_Clean_and_Mark = QtGui.QCheckBox(self.groupBox_3)
        self.Hydrant_Clean_and_Mark.setGeometry(QtCore.QRect(10, 158, 140, 18))
        self.Hydrant_Clean_and_Mark.setObjectName(_fromUtf8("Hydrant_Clean_and_Mark"))
        self.Mains_Valve_Repair = QtGui.QCheckBox(self.groupBox_3)
        self.Mains_Valve_Repair.setGeometry(QtCore.QRect(10, 200, 83, 18))
        self.Mains_Valve_Repair.setObjectName(_fromUtf8("Mains_Valve_Repair"))
        self.Mains_Valve_Replace = QtGui.QCheckBox(self.groupBox_3)
        self.Mains_Valve_Replace.setGeometry(QtCore.QRect(10, 220, 90, 18))
        self.Mains_Valve_Replace.setObjectName(_fromUtf8("Mains_Valve_Replace"))
        self.Main_repaired_replace_section = QtGui.QCheckBox(self.groupBox_3)
        self.Main_repaired_replace_section.setGeometry(QtCore.QRect(10, 50, 171, 18))
        self.Main_repaired_replace_section.setObjectName(_fromUtf8("Main_repaired_replace_section"))
        self.Replace_lid_Hydrant = QtGui.QCheckBox(self.groupBox_3)
        self.Replace_lid_Hydrant.setGeometry(QtCore.QRect(10, 180, 140, 18))
        self.Replace_lid_Hydrant.setObjectName(_fromUtf8("Replace_lid_Hydrant"))
        self.Replace_lid_Valve = QtGui.QCheckBox(self.groupBox_3)
        self.Replace_lid_Valve.setGeometry(QtCore.QRect(10, 240, 140, 18))
        self.Replace_lid_Valve.setObjectName(_fromUtf8("Replace_lid_Valve"))
        self.Replace_lid_Valve_2 = QtGui.QCheckBox(self.groupBox_3)
        self.Replace_lid_Valve_2.setGeometry(QtCore.QRect(10, 260, 140, 18))
        self.Replace_lid_Valve_2.setObjectName(_fromUtf8("Replace_lid_Valve_2"))
        self.groupBox_5 = QtGui.QGroupBox(WaterForm)
        self.groupBox_5.setGeometry(QtCore.QRect(220, 440, 191, 301))
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setChecked(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.Investigate = QtGui.QCheckBox(self.groupBox_5)
        self.Investigate.setGeometry(QtCore.QRect(11, 24, 87, 18))
        self.Investigate.setObjectName(_fromUtf8("Investigate"))
        self.Consumer_Problem = QtGui.QCheckBox(self.groupBox_5)
        self.Consumer_Problem.setGeometry(QtCore.QRect(11, 48, 113, 18))
        self.Consumer_Problem.setObjectName(_fromUtf8("Consumer_Problem"))
        self.Council_Facility = QtGui.QCheckBox(self.groupBox_5)
        self.Council_Facility.setGeometry(QtCore.QRect(11, 72, 93, 18))
        self.Council_Facility.setObjectName(_fromUtf8("Council_Facility"))
        self.Backfills_Cleanups = QtGui.QCheckBox(self.groupBox_5)
        self.Backfills_Cleanups.setGeometry(QtCore.QRect(10, 155, 102, 18))
        self.Backfills_Cleanups.setObjectName(_fromUtf8("Backfills_Cleanups"))
        self.Water_Sample = QtGui.QCheckBox(self.groupBox_5)
        self.Water_Sample.setGeometry(QtCore.QRect(10, 179, 91, 18))
        self.Water_Sample.setObjectName(_fromUtf8("Water_Sample"))
        self.Mains_Flushed = QtGui.QCheckBox(self.groupBox_5)
        self.Mains_Flushed.setGeometry(QtCore.QRect(10, 203, 91, 18))
        self.Mains_Flushed.setObjectName(_fromUtf8("Mains_Flushed"))
        self.Meter_Cover = QtGui.QCheckBox(self.groupBox_5)
        self.Meter_Cover.setGeometry(QtCore.QRect(10, 227, 129, 18))
        self.Meter_Cover.setObjectName(_fromUtf8("Meter_Cover"))
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(10, 251, 32, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.Other = QtGui.QLineEdit(self.groupBox_5)
        self.Other.setGeometry(QtCore.QRect(10, 270, 110, 20))
        self.Other.setObjectName(_fromUtf8("Other"))
        self.lab = QtGui.QLabel(self.groupBox_5)
        self.lab.setGeometry(QtCore.QRect(10, 100, 91, 16))
        self.lab.setObjectName(_fromUtf8("lab"))
        self.Provide_Location = QtGui.QComboBox(self.groupBox_5)
        self.Provide_Location.setGeometry(QtCore.QRect(70, 120, 101, 22))
        self.Provide_Location.setObjectName(_fromUtf8("Provide_Location"))
        self.Provide_Location.addItem(_fromUtf8(""))
        self.Provide_Location.setItemText(0, _fromUtf8(""))
        self.Provide_Location.addItem(_fromUtf8(""))
        self.Provide_Location.addItem(_fromUtf8(""))
        self.Provide_Location.addItem(_fromUtf8(""))
        self.Provide_Location.addItem(_fromUtf8(""))
        self.groupBox_4 = QtGui.QGroupBox(WaterForm)
        self.groupBox_4.setGeometry(QtCore.QRect(221, 231, 205, 203))
        self.groupBox_4.setCheckable(True)
        self.groupBox_4.setChecked(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.Pressure_Test_Service = QtGui.QCheckBox(self.groupBox_4)
        self.Pressure_Test_Service.setObjectName(_fromUtf8("Pressure_Test_Service"))
        self.gridLayout_4.addWidget(self.Pressure_Test_Service, 0, 0, 1, 3)
        self.Hydrant_Flow_Test = QtGui.QCheckBox(self.groupBox_4)
        self.Hydrant_Flow_Test.setObjectName(_fromUtf8("Hydrant_Flow_Test"))
        self.gridLayout_4.addWidget(self.Hydrant_Flow_Test, 4, 0, 1, 3)
        self.Pressure_Test_Hydrant = QtGui.QCheckBox(self.groupBox_4)
        self.Pressure_Test_Hydrant.setObjectName(_fromUtf8("Pressure_Test_Hydrant"))
        self.gridLayout_4.addWidget(self.Pressure_Test_Hydrant, 1, 0, 1, 3)
        self.Service_Flow_Test = QtGui.QCheckBox(self.groupBox_4)
        self.Service_Flow_Test.setObjectName(_fromUtf8("Service_Flow_Test"))
        self.gridLayout_4.addWidget(self.Service_Flow_Test, 5, 0, 1, 3)
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 2)
        self.Lockup_KPA = QtGui.QLineEdit(self.groupBox_4)
        self.Lockup_KPA.setObjectName(_fromUtf8("Lockup_KPA"))
        self.gridLayout_4.addWidget(self.Lockup_KPA, 2, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 6, 0, 1, 1)
        self.L_per_min = QtGui.QLineEdit(self.groupBox_4)
        self.L_per_min.setPlaceholderText(_fromUtf8(""))
        self.L_per_min.setObjectName(_fromUtf8("L_per_min"))
        self.gridLayout_4.addWidget(self.L_per_min, 6, 1, 1, 2)
        self.Test_Sheet_completed = QtGui.QCheckBox(self.groupBox_4)
        self.Test_Sheet_completed.setObjectName(_fromUtf8("Test_Sheet_completed"))
        self.gridLayout_4.addWidget(self.Test_Sheet_completed, 3, 0, 1, 1)

        self.retranslateUi(WaterForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), WaterForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), WaterForm.reject)
        QtCore.QMetaObject.connectSlotsByName(WaterForm)

    def retranslateUi(self, WaterForm):
        WaterForm.setWindowTitle(QtGui.QApplication.translate("WaterForm", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("WaterForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">WATER DAILY JOB SHEET</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("WaterForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">DESCRIPTION OF WORK</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("WaterForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Notes:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("WaterForm", "Service Installations and Meter Reads", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("WaterForm", "Installation Sheet No:", None, QtGui.QApplication.UnicodeUTF8))
        self.New_Service.setText(QtGui.QApplication.translate("WaterForm", "New Service", None, QtGui.QApplication.UnicodeUTF8))
        self.Fire_Service.setText(QtGui.QApplication.translate("WaterForm", "New Fire Service", None, QtGui.QApplication.UnicodeUTF8))
        self.Relayed_Service.setText(QtGui.QApplication.translate("WaterForm", "Relayed Service", None, QtGui.QApplication.UnicodeUTF8))
        self.Meter_Replaced.setText(QtGui.QApplication.translate("WaterForm", "Meter Replaced", None, QtGui.QApplication.UnicodeUTF8))
        self.Meter_Removed.setText(QtGui.QApplication.translate("WaterForm", "Meter Removed", None, QtGui.QApplication.UnicodeUTF8))
        self.Disconnect_Service.setText(QtGui.QApplication.translate("WaterForm", "Disconnect Service", None, QtGui.QApplication.UnicodeUTF8))
        self.Meter_Read.setText(QtGui.QApplication.translate("WaterForm", "Meter Read", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("WaterForm", "Existing Meter No:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("WaterForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Existing Meter</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Reading (KL):</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("WaterForm", "New Meter No:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("WaterForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">New Meter</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Reading (KL):</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("WaterForm", "Traffic Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("WaterForm", "Traffic Control Plan:", None, QtGui.QApplication.UnicodeUTF8))
        self.Traffic_Control_Plan_Used.setItemText(1, QtGui.QApplication.translate("WaterForm", "Diagram 1", None, QtGui.QApplication.UnicodeUTF8))
        self.Traffic_Control_Plan_Used.setItemText(2, QtGui.QApplication.translate("WaterForm", "Diagram 2", None, QtGui.QApplication.UnicodeUTF8))
        self.Traffic_Control_Plan_Used.setItemText(3, QtGui.QApplication.translate("WaterForm", "Diagram 3", None, QtGui.QApplication.UnicodeUTF8))
        self.Traffic_Control_Plan_Used.setItemText(4, QtGui.QApplication.translate("WaterForm", "Diagram 4", None, QtGui.QApplication.UnicodeUTF8))
        self.Traffic_Control_Plan_Used.setItemText(5, QtGui.QApplication.translate("WaterForm", "Diagram 5", None, QtGui.QApplication.UnicodeUTF8))
        self.Traffic_Control_Plan_Used.setItemText(6, QtGui.QApplication.translate("WaterForm", "Diagram 5a", None, QtGui.QApplication.UnicodeUTF8))
        self.Traffic_Control_Plan_Used.setItemText(7, QtGui.QApplication.translate("WaterForm", "Diagram 6", None, QtGui.QApplication.UnicodeUTF8))
        self.Traffic_Control_Plan_Used.setItemText(8, QtGui.QApplication.translate("WaterForm", "Diagram 7", None, QtGui.QApplication.UnicodeUTF8))
        self.Traffic_Control_Plan_Used.setItemText(9, QtGui.QApplication.translate("WaterForm", "Diagram 39", None, QtGui.QApplication.UnicodeUTF8))
        self.Traffic_Control_Plan_Used.setItemText(10, QtGui.QApplication.translate("WaterForm", "Diagram 43", None, QtGui.QApplication.UnicodeUTF8))
        self.Traffic_Control_Plan_Used.setItemText(11, QtGui.QApplication.translate("WaterForm", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("WaterForm", "Work  Duration (hrs)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("WaterForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">(Refer signage booklet for MUTCD</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">  for Short Term Works for Roads)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("WaterForm", "Signage Alterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("WaterForm", "Asset Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("WaterForm", "Pipe Material", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Material.setItemText(1, QtGui.QApplication.translate("WaterForm", "PVC", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Material.setItemText(2, QtGui.QApplication.translate("WaterForm", "AC", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Material.setItemText(3, QtGui.QApplication.translate("WaterForm", "CI", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Material.setItemText(4, QtGui.QApplication.translate("WaterForm", "CICL", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Material.setItemText(5, QtGui.QApplication.translate("WaterForm", "DICL", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Material.setItemText(6, QtGui.QApplication.translate("WaterForm", "Steel", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Material.setItemText(7, QtGui.QApplication.translate("WaterForm", "GI", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Material.setItemText(8, QtGui.QApplication.translate("WaterForm", "PE", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Material.setItemText(9, QtGui.QApplication.translate("WaterForm", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("WaterForm", "Pipe Diameter (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(1, QtGui.QApplication.translate("WaterForm", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(2, QtGui.QApplication.translate("WaterForm", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(3, QtGui.QApplication.translate("WaterForm", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(4, QtGui.QApplication.translate("WaterForm", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(5, QtGui.QApplication.translate("WaterForm", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(6, QtGui.QApplication.translate("WaterForm", "63", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(7, QtGui.QApplication.translate("WaterForm", "75", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(8, QtGui.QApplication.translate("WaterForm", "80", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(9, QtGui.QApplication.translate("WaterForm", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(10, QtGui.QApplication.translate("WaterForm", "110", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(11, QtGui.QApplication.translate("WaterForm", "150", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(12, QtGui.QApplication.translate("WaterForm", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(13, QtGui.QApplication.translate("WaterForm", "225", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(14, QtGui.QApplication.translate("WaterForm", "250", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(15, QtGui.QApplication.translate("WaterForm", "300", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(16, QtGui.QApplication.translate("WaterForm", "375", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(17, QtGui.QApplication.translate("WaterForm", "450", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(18, QtGui.QApplication.translate("WaterForm", "525", None, QtGui.QApplication.UnicodeUTF8))
        self.Pipe_Diameter.setItemText(19, QtGui.QApplication.translate("WaterForm", "600", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("WaterForm", "Pipe depth (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("WaterForm", "Joint Type", None, QtGui.QApplication.UnicodeUTF8))
        self.Joint_Type.setItemText(1, QtGui.QApplication.translate("WaterForm", "Rubber Ring", None, QtGui.QApplication.UnicodeUTF8))
        self.Joint_Type.setItemText(2, QtGui.QApplication.translate("WaterForm", "Flanged", None, QtGui.QApplication.UnicodeUTF8))
        self.Joint_Type.setItemText(3, QtGui.QApplication.translate("WaterForm", "Gibault", None, QtGui.QApplication.UnicodeUTF8))
        self.Joint_Type.setItemText(4, QtGui.QApplication.translate("WaterForm", "Welded", None, QtGui.QApplication.UnicodeUTF8))
        self.Joint_Type.setItemText(5, QtGui.QApplication.translate("WaterForm", "Solvent Welded", None, QtGui.QApplication.UnicodeUTF8))
        self.Joint_Type.setItemText(6, QtGui.QApplication.translate("WaterForm", "Flanged", None, QtGui.QApplication.UnicodeUTF8))
        self.Joint_Type.setItemText(7, QtGui.QApplication.translate("WaterForm", "Lead", None, QtGui.QApplication.UnicodeUTF8))
        self.Joint_Type.setItemText(8, QtGui.QApplication.translate("WaterForm", "Not Seen", None, QtGui.QApplication.UnicodeUTF8))
        self.Joint_Type.setItemText(9, QtGui.QApplication.translate("WaterForm", "Other ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("WaterForm", "Ground Conditions:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("WaterForm", "Valve Type", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Type.setItemText(1, QtGui.QApplication.translate("WaterForm", "Sluice", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Type.setItemText(2, QtGui.QApplication.translate("WaterForm", "Butterfly", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Type.setItemText(3, QtGui.QApplication.translate("WaterForm", "Scour", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Type.setItemText(4, QtGui.QApplication.translate("WaterForm", "PRV", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Type.setItemText(5, QtGui.QApplication.translate("WaterForm", "Reflux", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("WaterForm", "Valve Status", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Status.setItemText(1, QtGui.QApplication.translate("WaterForm", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Status.setItemText(2, QtGui.QApplication.translate("WaterForm", "Closed", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Status.setItemText(3, QtGui.QApplication.translate("WaterForm", "Zone", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Status.setItemText(4, QtGui.QApplication.translate("WaterForm", "Failed-Open", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Status.setItemText(5, QtGui.QApplication.translate("WaterForm", "Failed_Closed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("WaterForm", "Valve closing direction", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Closing_Direction.setItemText(1, QtGui.QApplication.translate("WaterForm", "Clockwise", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Closing_Direction.setItemText(2, QtGui.QApplication.translate("WaterForm", "Anti-clockwise", None, QtGui.QApplication.UnicodeUTF8))
        self.Valve_Closing_Direction.setItemText(3, QtGui.QApplication.translate("WaterForm", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("WaterForm", "Designation:", None, QtGui.QApplication.UnicodeUTF8))
        self.Designation.setItemText(1, QtGui.QApplication.translate("WaterForm", "Raw Water", None, QtGui.QApplication.UnicodeUTF8))
        self.Designation.setItemText(2, QtGui.QApplication.translate("WaterForm", "Distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.Designation.setItemText(3, QtGui.QApplication.translate("WaterForm", "Reticulation", None, QtGui.QApplication.UnicodeUTF8))
        self.Designation.setItemText(4, QtGui.QApplication.translate("WaterForm", "Constant Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.Designation.setItemText(5, QtGui.QApplication.translate("WaterForm", "Pressure System", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("WaterForm", "Scheme:", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(1, QtGui.QApplication.translate("WaterForm", "Warwick", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(2, QtGui.QApplication.translate("WaterForm", "Yangan", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(3, QtGui.QApplication.translate("WaterForm", "Stanthorpe", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(4, QtGui.QApplication.translate("WaterForm", "Killarney", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(5, QtGui.QApplication.translate("WaterForm", "Wallangarra", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(6, QtGui.QApplication.translate("WaterForm", "Allora", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(7, QtGui.QApplication.translate("WaterForm", "Dalveen", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(8, QtGui.QApplication.translate("WaterForm", "Pratten", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(9, QtGui.QApplication.translate("WaterForm", "Leyburn", None, QtGui.QApplication.UnicodeUTF8))
        self.Scheme.setItemText(10, QtGui.QApplication.translate("WaterForm", "Karara", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("WaterForm", "Response", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("WaterForm", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.Operators.setItemText(2, QtGui.QApplication.translate("WaterForm", "Kim", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("WaterForm", "Respond Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("WaterForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("WaterForm", "Completion Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("WaterForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("WaterForm", "Conections Interupted", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("WaterForm", "Interuption Duration (hrs)", None, QtGui.QApplication.UnicodeUTF8))
        self.Contacted_Consumer.setText(QtGui.QApplication.translate("WaterForm", "Contacted Consumer", None, QtGui.QApplication.UnicodeUTF8))
        self.Follow_up_Work_Required.setText(QtGui.QApplication.translate("WaterForm", "Follow up Work Required", None, QtGui.QApplication.UnicodeUTF8))
        self.Shutdown_Letter.setText(QtGui.QApplication.translate("WaterForm", "Shutdown Notification - letter", None, QtGui.QApplication.UnicodeUTF8))
        self.Shutdown_doorknock.setText(QtGui.QApplication.translate("WaterForm", "Shutdown Notification - door knock", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("WaterForm", "Request Details", None, QtGui.QApplication.UnicodeUTF8))
        self.Request_Type.setItemText(1, QtGui.QApplication.translate("WaterForm", "Water leak", None, QtGui.QApplication.UnicodeUTF8))
        self.Request_Type.setItemText(2, QtGui.QApplication.translate("WaterForm", "Leaking service", None, QtGui.QApplication.UnicodeUTF8))
        self.Request_Type.setItemText(3, QtGui.QApplication.translate("WaterForm", "Leaking meter", None, QtGui.QApplication.UnicodeUTF8))
        self.Request_Type.setItemText(4, QtGui.QApplication.translate("WaterForm", "Meter Won\'t turn off", None, QtGui.QApplication.UnicodeUTF8))
        self.Request_Type.setItemText(5, QtGui.QApplication.translate("WaterForm", "Valve", None, QtGui.QApplication.UnicodeUTF8))
        self.Request_Type.setItemText(6, QtGui.QApplication.translate("WaterForm", "Hydrant", None, QtGui.QApplication.UnicodeUTF8))
        self.Request_Type.setItemText(7, QtGui.QApplication.translate("WaterForm", "Water Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.Request_Type.setItemText(8, QtGui.QApplication.translate("WaterForm", "Low Water Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.Request_Type.setItemText(9, QtGui.QApplication.translate("WaterForm", "High Water Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.Request_Type.setItemText(10, QtGui.QApplication.translate("WaterForm", "Installation", None, QtGui.QApplication.UnicodeUTF8))
        self.Request_Type.setItemText(11, QtGui.QApplication.translate("WaterForm", "Programmed Maintenance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("WaterForm", "Request Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("WaterForm", "CR Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("WaterForm", "Requested By:", None, QtGui.QApplication.UnicodeUTF8))
        self.Requested_by.setItemText(1, QtGui.QApplication.translate("WaterForm", "Louis Van Slobbe", None, QtGui.QApplication.UnicodeUTF8))
        self.Requested_by.setItemText(2, QtGui.QApplication.translate("WaterForm", "Les Palmer", None, QtGui.QApplication.UnicodeUTF8))
        self.Requested_by.setItemText(3, QtGui.QApplication.translate("WaterForm", "Office", None, QtGui.QApplication.UnicodeUTF8))
        self.Requested_by.setItemText(4, QtGui.QApplication.translate("WaterForm", "Call Centre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("WaterForm", " Location Details:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("WaterForm", "Received:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("WaterForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.Drawing.setText(QtGui.QApplication.translate("WaterForm", "Drawing", None, QtGui.QApplication.UnicodeUTF8))
        self.Work_method_statement.setText(QtGui.QApplication.translate("WaterForm", "Work Method Statement Completed", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("WaterForm", "Service Repairs", None, QtGui.QApplication.UnicodeUTF8))
        self.Repaired_Service_clamp.setText(QtGui.QApplication.translate("WaterForm", "Repaired Service - clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.Repaired_Stop_Cock.setText(QtGui.QApplication.translate("WaterForm", "Repaired Stop cock", None, QtGui.QApplication.UnicodeUTF8))
        self.TPFNR_Repaired.setText(QtGui.QApplication.translate("WaterForm", "TPFNR Repaired", None, QtGui.QApplication.UnicodeUTF8))
        self.TPFNR_Replaced.setText(QtGui.QApplication.translate("WaterForm", "TPFNR Replaced", None, QtGui.QApplication.UnicodeUTF8))
        self.TPFNR_Capped.setText(QtGui.QApplication.translate("WaterForm", "TPFNR Capped", None, QtGui.QApplication.UnicodeUTF8))
        self.Replaced_Stop_Cock.setText(QtGui.QApplication.translate("WaterForm", "Replaced Stop cock", None, QtGui.QApplication.UnicodeUTF8))
        self.Repaired_Service_replace_section.setText(QtGui.QApplication.translate("WaterForm", "Repaired Service - replace section", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("WaterForm", "Mains and Fittings", None, QtGui.QApplication.UnicodeUTF8))
        self.Main_repaired_clamp.setText(QtGui.QApplication.translate("WaterForm", "Main Repaired - clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("WaterForm", "Failure Type", None, QtGui.QApplication.UnicodeUTF8))
        self.Failure_type.setItemText(1, QtGui.QApplication.translate("WaterForm", "Circular Fracture", None, QtGui.QApplication.UnicodeUTF8))
        self.Failure_type.setItemText(2, QtGui.QApplication.translate("WaterForm", "Longitudinal fracture", None, QtGui.QApplication.UnicodeUTF8))
        self.Failure_type.setItemText(3, QtGui.QApplication.translate("WaterForm", "Pipewall softening", None, QtGui.QApplication.UnicodeUTF8))
        self.Failure_type.setItemText(4, QtGui.QApplication.translate("WaterForm", "Pin hole", None, QtGui.QApplication.UnicodeUTF8))
        self.Failure_type.setItemText(5, QtGui.QApplication.translate("WaterForm", "Large Hole", None, QtGui.QApplication.UnicodeUTF8))
        self.Failure_type.setItemText(6, QtGui.QApplication.translate("WaterForm", "Joint", None, QtGui.QApplication.UnicodeUTF8))
        self.Failure_type.setItemText(7, QtGui.QApplication.translate("WaterForm", "Tapping", None, QtGui.QApplication.UnicodeUTF8))
        self.Failure_type.setItemText(8, QtGui.QApplication.translate("WaterForm", "Other Party Damage", None, QtGui.QApplication.UnicodeUTF8))
        self.Failure_type.setItemText(9, QtGui.QApplication.translate("WaterForm", "other", None, QtGui.QApplication.UnicodeUTF8))
        self.Hydrant_Repair.setText(QtGui.QApplication.translate("WaterForm", "Hydrant Repair", None, QtGui.QApplication.UnicodeUTF8))
        self.Hydrant_Replace.setText(QtGui.QApplication.translate("WaterForm", "Hydrant Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.Hydrant_Clean_and_Mark.setText(QtGui.QApplication.translate("WaterForm", "Hydrant Clean and Mark", None, QtGui.QApplication.UnicodeUTF8))
        self.Mains_Valve_Repair.setText(QtGui.QApplication.translate("WaterForm", "Valve Repair", None, QtGui.QApplication.UnicodeUTF8))
        self.Mains_Valve_Replace.setText(QtGui.QApplication.translate("WaterForm", "Valve Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.Main_repaired_replace_section.setText(QtGui.QApplication.translate("WaterForm", "Main Repaired - replace section", None, QtGui.QApplication.UnicodeUTF8))
        self.Replace_lid_Hydrant.setText(QtGui.QApplication.translate("WaterForm", "Replace Lid - Hydrant", None, QtGui.QApplication.UnicodeUTF8))
        self.Replace_lid_Valve.setText(QtGui.QApplication.translate("WaterForm", "Replace Lid - Valve", None, QtGui.QApplication.UnicodeUTF8))
        self.Replace_lid_Valve_2.setText(QtGui.QApplication.translate("WaterForm", "Replace Markers", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("WaterForm", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.Investigate.setText(QtGui.QApplication.translate("WaterForm", "Investigation", None, QtGui.QApplication.UnicodeUTF8))
        self.Consumer_Problem.setText(QtGui.QApplication.translate("WaterForm", "Consumer Problem", None, QtGui.QApplication.UnicodeUTF8))
        self.Council_Facility.setText(QtGui.QApplication.translate("WaterForm", "Council Facility", None, QtGui.QApplication.UnicodeUTF8))
        self.Backfills_Cleanups.setText(QtGui.QApplication.translate("WaterForm", "Backfill/cleanups", None, QtGui.QApplication.UnicodeUTF8))
        self.Water_Sample.setText(QtGui.QApplication.translate("WaterForm", "Water Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.Mains_Flushed.setText(QtGui.QApplication.translate("WaterForm", "Mains Flushed", None, QtGui.QApplication.UnicodeUTF8))
        self.Meter_Cover.setText(QtGui.QApplication.translate("WaterForm", "Meter Cover Provided", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("WaterForm", "Other:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab.setText(QtGui.QApplication.translate("WaterForm", "Provide Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.Provide_Location.setItemText(1, QtGui.QApplication.translate("WaterForm", "External Customer", None, QtGui.QApplication.UnicodeUTF8))
        self.Provide_Location.setItemText(2, QtGui.QApplication.translate("WaterForm", "Parks", None, QtGui.QApplication.UnicodeUTF8))
        self.Provide_Location.setItemText(3, QtGui.QApplication.translate("WaterForm", "Buildings", None, QtGui.QApplication.UnicodeUTF8))
        self.Provide_Location.setItemText(4, QtGui.QApplication.translate("WaterForm", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("WaterForm", "Pressure and Flow", None, QtGui.QApplication.UnicodeUTF8))
        self.Pressure_Test_Service.setText(QtGui.QApplication.translate("WaterForm", "Pressure Test Service", None, QtGui.QApplication.UnicodeUTF8))
        self.Hydrant_Flow_Test.setText(QtGui.QApplication.translate("WaterForm", "Hydrant Flow Test", None, QtGui.QApplication.UnicodeUTF8))
        self.Pressure_Test_Hydrant.setText(QtGui.QApplication.translate("WaterForm", "Pressure Test Hydrant", None, QtGui.QApplication.UnicodeUTF8))
        self.Service_Flow_Test.setText(QtGui.QApplication.translate("WaterForm", "Service Flow Test", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("WaterForm", "Lockup (KPA):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("WaterForm", "(L/min):", None, QtGui.QApplication.UnicodeUTF8))
        self.Test_Sheet_completed.setText(QtGui.QApplication.translate("WaterForm", "Test Sheet completed", None, QtGui.QApplication.UnicodeUTF8))

