@ECHO OFF

SET OSGEO4W_ROOT=C:\OSGeo4W
PATH=%OSGEO4W_ROOT%\bin;%PATH%
SET PYTHONHOME=%OSGEO4W_ROOT%\apps\Python27
SET PATH=%PATH%;%OSGEO4W_ROOT%\apps\Python27\Scripts
SET QGIS_PLUGINPATH=%~dp0
SET PYTHONPATH=qmap\qtcontrols;%~dp0;%PYTHONPATH%
SET PYQTDESIGNERPATH=qmap\qtcontrols\plugins